<?php /* @var \WeltPixel\OwlCarouselSlider\Block\Slider\Products $this */ ?>

<?php $sliderData    = $this->getSliderConfiguration(); ?>
<?php $enabled       = array_key_exists('status', $sliderData) ? $sliderData['status'] : ''; ?>
<?php $showPrice     = array_key_exists('show_price', $sliderData) ? $sliderData['show_price'] : false; ?>
<?php $showAddToCart = array_key_exists('show_addto', $sliderData) ? $sliderData['show_addto'] : false; ?>
<?php $showWishlist  = (array_key_exists('show_wishlist', $sliderData) && $sliderData['show_wishlist'] !=0) ? true : false; ?>
<?php $showCompare   = (array_key_exists('show_compare', $sliderData) && $sliderData['show_compare'] !=0) ? true : false; ?>
<?php if(!$enabled){ return; } ?>

<?php
$products = $this->getProductCollection();

if(!count($products)) { return; }

$productsType = $this->getData('products_type');
$sliderConfig = json_encode($sliderData);
$sliderTitle  = array_key_exists('title', $sliderData) ? $sliderData['title'] : '';
$breakpoint   = $this->getBreakpointConfiguration();

?>

<div class="custom-slider">
    <?php if (trim($sliderTitle)) : ?>
    <div class="content-heading">
        <h2 class="title"><?php echo $sliderTitle; ?></h2>
    </div>
    <?php endif; ?>
    <div class="products-grid grid-3 owl-carousel-products-<?php echo $productsType;?><?php echo count($products)== 1? '-single-item': '';?>">
        <?php foreach($products as $product) : ?>

            <?php
            $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
            $productImage = $_imagehelper->init($product, 'category_page_list')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(400)->getUrl();
            $productUrl   =  $product->getUrlModel()->getUrl($product);
            ?>

			<div class="item">
				<div class="product-content">
					<div class="product-image">
						<img alt="<?php echo $product->getName(); ?>" src="<?php echo $productImage; ?>" class=""
                                    <?php echo $sliderData['lazyLoad'] ? 'data-src="' . $productImage . '" data-src-retina="' . $productImage . '" class="owl-lazy"' : '' ?>
                                />
					</div>
					<div class="actions-secondary" data-role="add-to-links">
						<?php if ($showWishlist || $showCompare): ?>
							<div class="secondary-addto-links actions-secondary" data-role="add-to-links">
								<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
									<a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($product); ?>'  class="action towishlist" data-action="add-to-wishlist" title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
										<span class="fa fa-heart"></span>
									</a>
								<?php endif; ?>

								<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
									<?php
									$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
									?>
									<a href="#" class="action tocompare"
									   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($product);?>'
									   data-role="add-to-links"
									   title="<?php /* @escapeNotVerified */ echo __('Add to Compare'); ?>">
										<span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
									</a>
								<?php endif; ?>
							</div>
						<?php endif; ?>
					</div>
					
					<div class="product-details">
						<h4 class="product-name"> <?php echo $product->getName(); ?></h4>
						<span class="price">
							<?php if($showPrice) : ?>
								<?php /* @escapeNotVerified */ echo $this->getProductPrice($product); ?>
							<?php endif; ?>
						</span>
					</div>
					<div class="action">
						<?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
							$postData = $postDataHelper->getPostData($block->getAddToCartUrl($product), ['product' => $product->getEntityId()]) ?>
						<button class="fill add-to-cart fixed left"
								data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
								type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
							<span><?php /* @escapeNotVerified */ echo __('Add to cart') ?></span>
						</button>
						<button class="view-more-button right fixed" onclick="window.location('<?php echo $productUrl; ?>')">Explore</button>
					</div>
				</div>
			</div>

			
        <?php endforeach; ?>
    </div>
    <div id="pre-div">
        <div class="cssload-loader">
            <div class="cssload-inner cssload-one"></div>
            <div class="cssload-inner cssload-two"></div>
            <div class="cssload-inner cssload-three"></div>
        </div>
    </div>
</div>

<script>
    require(['jquery', 'owl_carousel', 'owl_config', 'owl_config' ],
        function ($) {
            $(document).ready(function(){
                var products_type = '<?php echo $productsType;?>',
                    slider_config = <?php echo $sliderConfig; ?>,

                    carouselElement = $('.owl-carousel-products-' + products_type),

                    items = ((slider_config.items >= 0 && slider_config.items != null) ? slider_config.items : 2),

                    stagePadding = slider_config.stagePadding != '' ? parseInt(slider_config.stagePadding) : 0,

                    sPBrk_1 = slider_config.stagePadding_brk1 != '' ? parseInt(slider_config.stagePadding_brk1) : 0,
                    sPBrk_2 = slider_config.stagePadding_brk2 != '' ? parseInt(slider_config.stagePadding_brk2) : 0,
                    sPBrk_3 = slider_config.stagePadding_brk3 != '' ? parseInt(slider_config.stagePadding_brk3) : 0,
                    sPBrk_4 = slider_config.stagePadding_brk4 != '' ? parseInt(slider_config.stagePadding_brk4) : 0;

                options = {
                    nav                 :parseInt(slider_config.nav) == 1 ? true : false,
                    dots                :parseInt(slider_config.dots) == 1 ? true : false,
                    center              :parseInt(slider_config.center) == 1 ? true : false,
                    items               :items,
                    loop                :parseInt(slider_config.loop) == 1 ? true : false,
                    margin              :parseInt(slider_config.margin) != '' ? parseInt(slider_config.margin) : 0,
                    stagePadding        :parseInt(slider_config.center) == 1 ? 0 : stagePadding,
                    lazyLoad            :parseInt(slider_config.lazyLoad) == 1 ? true : false,
                    autoplay            :parseInt(slider_config.autoplay) == 1 ? true : false,
                    autoplayTimeout     :(slider_config.autoplayTimeout > 0 && slider_config.autoplayTimeout != null) ? parseInt(slider_config.autoplayTimeout) : 3000,
                    autoplayHoverPause  :parseInt(slider_config.autoplayHoverPause) == 1 ? true : false,
                    autoHeight          :false,

                    responsive:{
                        <?php echo $breakpoint['breakpoint_1']; ?>:{
                            nav             :parseInt(slider_config.nav_brk1) == 1 ? true : false,
                            dots            :parseInt(slider_config.dots_brk1) == 1 ? true : false,
                            items           :(slider_config.items_brk1  >= 0 && slider_config.items_brk1 != null) ? parseInt(slider_config.items_brk1) : items,
                            center          :parseInt(slider_config.center_brk1) == 1 ? true : false,
                            stagePadding    :parseInt(slider_config.center) == 1 ? 0 : sPBrk_1
                        },
                        <?php echo $breakpoint['breakpoint_2']; ?>:{
                            nav             :parseInt(slider_config.nav_brk2) == 1 ? true : false,
                            dots            :parseInt(slider_config.dots_brk2) == 1 ? true : false,
                            items           :(slider_config.items_brk2  >= 0 && slider_config.items_brk2 != null) ? parseInt(slider_config.items_brk2) : items,
                            center          :parseInt(slider_config.center_brk2) == 1 ? true : false,
                            stagePadding    :parseInt(slider_config.center) == 1 ? 0 : sPBrk_2
                        },
                        <?php echo $breakpoint['breakpoint_3']; ?>:{
                            nav             :parseInt(slider_config.nav_brk3) == 1 ? true : false,
                            dots            :parseInt(slider_config.dots_brk3) == 1 ? true : false,
                            items           :(slider_config.items_brk3  >= 0 && slider_config.items_brk3 != null) ? parseInt(slider_config.items_brk3) : items,
                            center          :parseInt(slider_config.center_brk3) == 1 ? true : false,
                            stagePadding    :parseInt(slider_config.center) == 1 ? 0 : sPBrk_3
                        },
                        <?php echo $breakpoint['breakpoint_4']; ?>:{
                            nav             :parseInt(slider_config.nav_brk4) == 1 ? true : false,
                            dots            :parseInt(slider_config.dots_brk4) == 1 ? true : false,
                            items           :(slider_config.items_brk4  >= 0 && slider_config.items_brk4 != null) ? parseInt(slider_config.items_brk4) : items,
                            center          :parseInt(slider_config.center_brk4) == 1 ? true : false,
                            stagePadding    :parseInt(slider_config.center) == 1 ? 0 : sPBrk_4,
							
                        }
                    }
                };
				
				// workaround for owl carousel
				// fix nav buttons display on load even when set as false
				carouselElement.on('initialized.owl.carousel', function(event) {
					setTimeout(function(){
						carouselElement.trigger('next.owl.carousel');
					}, 370);
				});

				carouselElement.owlCarousel(options);

            });
        });
</script>
