<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$myBlock = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Catalog\Block\Product\View');
$_product = $myBlock->getProduct();
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$title = '';
if (trim($block->getPageHeading())) {
    $title = '<span class="base" data-ui-id="page-title-wrapper" ' .  $block->getAddBaseAttribute() . '>'
        . $block->escapeHtml($block->getPageHeading()) . '</span>';
}
?>
<?php if ($title): ?>
<div class="page-title-wrapper<?php /* @escapeNotVerified */ echo $cssClass; ?>">
    <h1 class="page-title"
        <?php if ($block->getId()): ?> id="<?php /* @escapeNotVerified */ echo $block->getId();?>" <?php endif; ?>
        <?php if ($block->getAddBaseAttributeAria()): ?>
            aria-labelledby="<?php /* @escapeNotVerified */ echo $block->getAddBaseAttributeAria(); ?>"
        <?php endif; ?>>
        <?php /* @escapeNotVerified */ echo $title ?>
    </h1>
	<h5 class="artist_sec"><span class="title_creason"><?php if(!empty($_product)){echo $description = $this->helper('Magento\Catalog\Helper\Output')->productAttribute($myBlock->getProduct(), $myBlock->getProduct()->getShortDescription(), 'short-description');}?></span>
    <!--<span class="artist_name">By: Sam Roy</span>--></h5>
	<span class="model_name">For: iPhone 6</span>
    <?php echo $block->getChildHtml(); ?>
</div>
<?php endif; ?>
