<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
	
    <div class="products category_products wrapper grid<?php /* @escapeNotVerified */ //echo $viewMode; ?> products-grid<?php /* @escapeNotVerified */ //echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): 
            $productattributes = $objectManager->get('Magento\Catalog\Model\Product')->load($_product->getId());
            $catIds = $_product->getCategoryIds(); //print_r($catIds); exit;
                if(count($catIds) ){
                   foreach($catIds as $Id){
                    $category = $objectManager->create('Magento\Catalog\Model\category')->load($Id);
                    $categoryDetails = $category->getData();
                    if($categoryDetails['level'] == 2){
                        $urlKey = $categoryDetails['url_key'];
                    }
                   }
                } 
            ?>
                <?php
                 $check_img = $_product->getData('small_image');
                if($check_img != 'no_selection'){
                    if($check_img != ''){
                 /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php echo $productImage->toHtml(); ?>
                    </a>
					<div class="wish-block">
						<div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
							<?php if ($addToBlock = $block->getChildBlock('addto')): ?>
								<?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
							<?php endif; ?>
						</div>
					</div>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($productattributes->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ $design=$productattributes->getData('product_design'); 
                                if(!$design){echo $_helper->productAttribute($_product, $_product->getName(), 'name');}else{echo $design;} 
                                //echo $productattributes->getData('product_design');
                                ?>
                            </a>
                        </strong>
                        <?php $tagLine = $productattributes->getData('tag_line');
                        //print_r($catIds); exit;
                        if(count($catIds) ){
                           foreach($catIds as $Id){
                            $category = $objectManager->create('Magento\Catalog\Model\category')->load($Id);
                            $categoryDetails = $category->getData(); 
                            if(!empty($categoryDetails)){
                            $categories = explode("/",$categoryDetails['url_path']);
                            $urlKey="";                            
                            if(!empty($categories)){
                            $urlKey = $categories[0];
                            } 
                            }  
                           }
                        } 
                        if((!empty($tagLine)) && ($urlKey != "phone-cases")) {?>
						<span class="product_sub_detail"><?php echo $tagLine;?></span>
                        <?php 
                        }
                        $model = $productattributes->getResource()->getAttribute('model')->getFrontend()->getValue($_product);
                        $attribute_model = explode("-", $model);//print_r($attribute_model);
                        if(!empty($attribute_model[1])){
                        $attribute_model = $attribute_model[1];} else {
                        $attribute_model =  $model;
                        }
                        $caseType = $productattributes->getResource()->getAttribute('case_type')->getFrontend()->getValue($_product);
                        $brand = $productattributes->getResource()->getAttribute('brand')->getFrontend()->getValue($_product);

                        ?>
						<span class="product_model"><?php if($caseType != "No"){echo "Type: ".$caseType." Case For ".$brand."  ".$attribute_model."";}?></span><?php //}?>
                        <!--<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>-->
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                        <!--<?php echo $block->getProductDetailsHtml($_product); ?>-->

                        <!--<div class="product-item-inner">
                            <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey')?>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                       class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>-->
                    </div>
                </div>
                <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
                <?php }
                }
                 ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
