<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('parentCategory')->toHtml();?>


<!--<div class="category-container section-cotainer">
	<div class="columns-grid grid-3">
		<div class="grid">
			<div class="category-box">
				<div class="category-img">
					<img src="<?php echo $this->getViewFileUrl('Magento_Cms::images/cases.jpg');?>" alt="category-1"/>
				</div>
				<div class="category-title">
					<a href="#"><h4 class="category-name">MOBILE <br> CASES</h4></a>
				</div>
			</div>
		</div>
		
		<div class="grid">
			<div class="category-box">
				<div class="category-img">
					<img src="<?php echo $this->getViewFileUrl('Magento_Cms::images/cases.jpg');?>" alt="category-1"/>
				</div>
				<div class="category-title">
					<a href="#"><h4 class="category-name">MOBILE <br> CASES</h4></a>
				</div>
			</div>
		</div>
		
		<div class="grid">
			<div class="category-box">
				<div class="category-img">
					<img src="<?php echo $this->getViewFileUrl('Magento_Cms::images/cases.jpg');?>" alt="category-1"/>
				</div>
				<div class="category-title">
					<a href="#"><h4 class="category-name">MOBILE <br> CASES</h4></a>
				</div>
			</div>
		</div>
		
		<div class="grid">
			<div class="category-box">
				<div class="category-img">
					<img src="<?php echo $this->getViewFileUrl('Magento_Cms::images/cases.jpg');?>" alt="category-1"/>
				</div>
				<div class="category-title">
					<a href="#"><h4 class="category-name">MOBILE <br> CASES</h4></a>
				</div>
			</div>
		</div>
		
		<div class="grid">
			<div class="category-box">
				<div class="category-img">
					<img src="<?php echo $this->getViewFileUrl('Magento_Cms::images/cases.jpg');?>" alt="category-1"/>
				</div>
				<div class="category-title">
					<a href="#"><a href="#"><h4 class="category-name">MOBILE <br> CASES</h4></a></a>
				</div>
			</div>
		</div>
		
		<div class="grid last">
			<div class="category-box">
				<div class="category-img">
				</div>
				<div class="category-title">
					<a href="#"><h4 class="category-name">VIEW <br> MORE</h4></a>
				</div>
			</div>
		</div>
	</div>
</div>-->
