<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
if($_POST){
 $to = "care@desiredesire.com";
 $subject = "Customer Query - You can write to us";
 $body = $_POST['comment'];
 mail($to, $subject, $body);
}
?>
<div class="contact_page">
	<div class="contact_upper-section">
		<div class="main-title">
			<p>We are always happy to receive feedback</p>
			<p>Also glad to answer queries</p>
		</div>
		<div class="sub-title">The more we hear from you, the better we get.</div>
		<div class="contact-detail-section">
			<div class="contact-content">
				<div class="msg-box">
					<p class="box-txt">You can write to us</p>
					<div class="msg-form">
						<form class="form contact" action="" id="contact-form"
							  method="post" data-hasrequired="<?php echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
							<fieldset class="fieldset">
								<div class="field name required input_section">
									<input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Name'" placeholder="Name" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
								</div>
								<div class="field email required input_section">
									<input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email'" placeholder="Email" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
								</div>
								<div class="field telephone input_section">
									<input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Telephone') ?>" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Telephone'" placeholder="Telephone" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>" class="input-text" type="text" />
								</div>
								<div class="field comment required input_section">
									<textarea name="comment" id="comment" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Your message'" placeholder="Your message" title="<?php /* @escapeNotVerified */ echo __('Your message') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
								</div>
								<?php echo $block->getChildHtml('form.additional.info'); ?>
							</fieldset>
							<div class="actions-toolbar">
								<div class="primary">
									<input type="hidden" name="hideit" id="hideit" value="" />
									<button type="submit" id="msg" title="<?php /* @escapeNotVerified */ echo __('Send') ?>" class="action submit primary">
										<span><?php /* @escapeNotVerified */ echo __('Send') ?></span>
									</button>
								</div>
							</div>
						</form>	
						<div>
							<p id="success-msg"></p>
							
						</div>		
					</div>
				</div>
				<div class="call-box">
					<p class="box-txt">or Call us</p>
					<div class="call-sec">
						<img class="call_img" alt="" src="<?php echo $this->getViewFileUrl('images/call.jpg');?>" >
						<p>+91 88805 67111</p>
						<p>(Mon &ndash; Fri, 10:00 am &ndash; 06:00 pm)</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
require(['jquery'],function($){
		
jQuery(document).ready(function() {
	
	jQuery('#msg').on('click', function(){
		jQuery('#contact-form').submit(function() {
			jQuery("#success-msg").fadeIn("slow").append('Thank you. We will be in touch');
       	    jQuery("#success-msg").fdelay(30000).fadeOut();  	    
	
    });
	});
});
});
</script>