<div class="dash-info-title">
	<ul>
		<li>
			<h3> Recent Orders</h3>
		</li>
		<li>
			<a href="#">View all</a>
		</li>
		<li>
			<p>|</p>
		</li>
		<li>
			<a href="#">Completed</a>
		</li>
		<li>
			<a href="#">Pending</a>
		</li>
		<li>
			<a href="#">Cancelled</a>
		</li>
	</ul>
</div>
<div class="recent-orders-discription">
	<div class="recent-orders-header">
		<div class="row">
			<div class="col-md-8">
				<div class="row">
					<div class="col-md-2">
						<h5>Order Date</h5>
						<h6>29/10/2016</h6>
					</div>
					<div class="col-md-2">
						<h5>Delivery</h5>
						<h4>In Transit</h4>
					</div>
					<div class="col-md-2">
						<h5>Total</h5>
						<h6>Rs.1500</h6>
					</div>
					<div class="col-md-2">
						<h5>Ship to</h5>
						<h4>Tom Jose</h4>
					</div>
					<div class="col-md-2">
						<h5>Status</h5>
						<h4>Pending</h4>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				
					<h5>Order #: 1033300321</h5>
					<h4>Order Details</h4>
				
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8">
			<div class="row">
				<div class="col-md-2">
					<img src="<?php echo $this->getViewFileUrl('Magento_Catalog::images/images/.png');?>" alt="img">
				</div>
				<div class="col-md-10">
					<div class="recent-orders-header-description">
						<h4>The Trabola</h4>
						<p>Lorem ipsum dolor sit amet, consectetuer Lorem ipsum dolor sit amet, consectetuer</p>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="recent-orders-header-btn">
				<a href="#">Track Order</a>
				<a href="#">Write a review</a>
				<a href="#">Cancel or Return order</a>
			</div>
		</div>
	</div>
</div>