<div class="track_order_container">
	<div class="track_order-content">
		<div class="track_order_heading">
			<h4>Track Order</h4>
		</div>
		<div class="track_order_data">
			<div class="order_id">
				<span class="order_label">Order #: </span><span class="track_id">103212324546</span>
			</div>
			<div class="order-status col-lg-12 col-md-12 col-sm-12 col-xs-12">
				<div class="col-lg-3 col-md-3 col-sm-3 col-xs-4 status_state">
					<div class="track_line">
						<span class="order-crcl"></span>
						<span class="order-tick"></span>
						<span class="order-red-line"></span>
					</div>
					<div class="order_tag">
						<span class="tag_label">Ordered:</span>
						<span class="tag_data">24 Sep 2017</span>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 col-xs-4 status_state">
					<div class="track_line">
						<span class="order-crcl"></span>
						<span class="order-tick"></span>
						<span class="order-red-line"></span>
					</div>
					<div class="order_tag">
						<span class="tag_label">Shipped:</span>
						<span class="tag_data">24 Sep 2017</span>
					</div>
				</div>
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-4 status_state right_align">
					<div class="track_line">
						<span class="order-crcl"></span>
						<span class="order-tick"></span>
						<span class="order-red-line"></span>
					</div>
					<div class="order_tag">
						<span class="tag_label">Est. Delivery:</span>
						<span class="tag_data">1 Oct 2017</span>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 col-xs-4 status_state second-line">
					<div class="order_tag">
						<span class="tag_label">Ship to:</span>
						<span class="tag_data">
							<span class="cst_name">Tom Jose</span>
							<span class="cst_address">#22, Haskar Hosur Road 2nd Floor, Opp. Adogodi Police Station Bangaluru, Karnataka 560030</span>
						</span>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 col-xs-4 status_state second-line">
					<span class="shipped_prodcut">
						<img src="images/product_thumbnail_img.jpg" rel="" title="" />
					</span>
				</div>
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-4 status_state mob-sec second-line">
					<div class="order_detail_link">Order Details<span class="rit-arrow"></span></div>
				</div>
			</div>
		</div>
	</div>
</div>