<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="position_relative">
<?php echo $block->getChildHtml('form_before')?>
	<div class="titl_bar">
		<h1 class="page_titl">Newsletter Subscription</h1>
		<a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span class="left_arrow"><i class="fa fa-chevron-left" aria-hidden="true"></i></span><span class="txt"><?php /* @escapeNotVerified */ echo __('Back') ?></span></a>
	</div>
	<div class="account_content">
    <form class="form form-newsletter-manage" action="<?php /* @escapeNotVerified */ echo $block->getAction() ?>" method="post" id="form-validate">
            <?php echo $block->getBlockHtml('formkey')?>
            <div class="page_title_div"><h3><?php /* @escapeNotVerified */ echo __('Subscription option') ?></h3></div> 
			<div class="content_section">
                <input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?php /* @escapeNotVerified */ echo __('General Subscription') ?>"<?php if ($block->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox">
                <label for="subscription" class="label"><span><?php /* @escapeNotVerified */ echo __('General Subscription') ?></span></label>
            </div>
            <?php /* Extensions placeholder */ ?>
            <?php echo $block->getChildHtml('customer.form.newsletter.extra')?>
			<div class="actions-toolbar">
			<div class="primary"><button type="submit" title="<?php /* @escapeNotVerified */ echo __('Save') ?>" class="action save primary"><span><?php /* @escapeNotVerified */ echo __('Save') ?></span></button></div>
			</div>
    </form>
	<?php /* Extensions placeholder */ ?>
	<?php echo $block->getChildHtml('customer.form.newsletter.extra2')?>
	</div>
</div>