<?php
/**
 * 
 */
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_product = $block->getProduct();
    
?>

<div class="desire-pd-tab">	
	<!--<div class="Desc-hed">Description</div>-->
		<?php $shortDescription = $this->helper('Magento\Catalog\Helper\Output')->productAttribute($block->getProduct(), $block->getProduct()->getShortDescription(), 'short-description'); ?>
		<?php
		$short_data = strip_tags($shortDescription);
		if (strlen($short_data) > 300) {
						$stringCut = substr($short_data, 0, 300);
						$short_data = substr($stringCut, 0, strrpos($stringCut, ' ')).'...'; 
					}
		 ?>
		<div class="showing_txt"><?php echo $short_data; ?></div>
		<span class="show_txt">Read More</span>
		<?php $shortDescription = $this->helper('Magento\Catalog\Helper\Output')->productAttribute($block->getProduct(), $block->getProduct()->getShortDescription(), 'short-description'); ?>
		<div class="disable_txt"><?php echo $shortDescription ?></div>
		<span class="hide_txt">Read Less</span>
</div>
<script type="text/javascript">
require(['jquery'],function($){
    jQuery(document).ready(function(){
        
		jQuery(".show_txt").click(function(){
			jQuery(".show_txt").addClass('remove');
			jQuery(".hide_txt").addClass('showthis');
			jQuery(".showing_txt").slideUp();
			jQuery(".disable_txt").slideDown();
		});
		jQuery(".hide_txt").click(function(){
			jQuery(".hide_txt").removeClass('showthis');
			jQuery(".disable_txt").slideUp();
			jQuery(".showing_txt").slideDown();
			jQuery(".show_txt").removeClass('remove');
			
		});
    });
});

/*$(document).ready(function() {
  
    var cutCount = 2;
  
    $("#testID p").each(function (i) {
        i++;
        if(i == cutCount) {
            $(this).append(' <a href="javascript:void(1)" onclick="$(\'#testID p\').show(); $(this).hide()">Read more</b>')   
        }
        if(i > cutCount) {
           $(this).hide();
        }
    });*/
    
</script>