<div class="desire-pd-tab">					  
  <input id="tab1" type="radio" name="tabs" checked>
  <label for="tab1">Description</label>
  <input id="tab2" type="radio" name="tabs">
  <label for="tab2">Tech Specs </label>
  <input id="tab3" type="radio" name="tabs">
  <label for="tab3">About the Artist</label>
  <section id="content1">
	<p>
	  Casio was established in April 1946 by Tadao Kashio, an engineer specializing in fabrication technology. Kashio's first major product was the Yubiwa Pipe, a finger ring that would hold a cigarette, allowing the wearer to smoke the cigarette down to its nub while also leaving the wearer's hands free.
	</p>
  </section>
  <section id="content2">
	<p>
	  Bacon ipsum dolor sit amet landjaeger sausage brisket, jerky drumstick fatback boudin ball tip turducken. Pork belly meatball t-bone bresaola tail filet mignon kevin turkey ribeye shank flank doner cow kielbasa shankle. Pig swine chicken hamburger, tenderloin turkey rump ball tip sirloin frankfurter meatloaf boudin brisket ham hock. Hamburger venison brisket tri-tip andouille pork belly ball tip short ribs biltong meatball chuck.
	</p>
  </section>
  <section id="content3">
	<p>
	  Bacon ipsum dolor sit amet beef venison beef ribs kielbasa. Sausage pig leberkas, t-bone sirloin shoulder bresaola. Frankfurter rump porchetta ham. Pork belly prosciutto brisket meatloaf short ribs.
	</p>
  </section>
</div>
