<?php
    $categories = $this->getCategoryCollection();
    $categoryHelper = $this->getCategoryHelper();
   // print_r($categories); exit;
?>

<?php if($this->getViewType() != "list"){ ?>
<div class="category-container section-cotainer">
	<div class="category-main-title">
		<h3>Desireables</h3>
	</div> 
    <div class="columns-grid grid-2" id="homepage-category-carousel">
        <?php 
        $sortrder = array(5,3,10,11);
       $data = array();
        foreach($categories as $category){ 

            $cat = $this->getCategorymodel($category->getId());
            $data['imageurl'] = $cat->getImageUrl();
            $data['name'] = $cat->getName();
            $data['url'] = $cat->getUrl();
            $datacollection[] = $data;

        }?>

       <?php //if($image != null): ?>
                <div class="grid">
                    <div class="category-box" style="background-image: url(<?php echo $datacollection[1]['imageurl'];?>)">
                        <div class="category-img">
                            <img src="<?php echo $datacollection[1]['imageurl'];?>" alt="<?php echo $datacollection[1]['name']?>"/>
                        </div>
                        <div class="category-title">
                            <a href="<?php echo $datacollection[1]['url'];?>"><h4 class="category-name"><?php echo wordwrap($datacollection[1]['name'], 8, "<br>\n", false); ?></h4></a>
                        </div>
                    </div>
                </div>
            <?php 
           // endif;?>
             <?php //if($image != null): ?>
                <div class="grid">
                    <div class="category-box" style="background-image: url(<?php echo $datacollection[3]['imageurl'];?>)">
                        <div class="category-img">
                            <img src="<?php echo $datacollection[3]['imageurl'];?>" alt="<?php echo $datacollection[3]['name']?>"/>
                        </div>
                        <div class="category-title">
                            <a href="<?php echo $datacollection[3]['url'];?>"><h4 class="category-name"><?php echo wordwrap($datacollection[3]['name'] , 8, "<br>\n", false);?></h4></a>
                        </div>
                    </div>
                </div>
            <?php 
           // endif;?>
             <?php //if($image != null): ?>
                <div class="grid">
                    <div class="category-box" style="background-image: url(<?php echo $datacollection[0]['imageurl'];?>)">
                        <div class="category-img">
                            <img src="<?php echo $datacollection[0]['imageurl'];?>" alt="<?php echo $datacollection[0]['name']?>"/>
                        </div>
                        <div class="category-title">
                            <a href="<?php echo $datacollection[0]['url'];?>"><h4 class="category-name"><?php echo wordwrap($datacollection[0]['name'] , 8, "<br>\n", false);?></h4></a>
                        </div>
                    </div>
                </div>
            <?php 
            //endif;?>
             <?php //if($image != null): ?>
                <div class="grid">
                    <div class="category-box" style="background-image: url(<?php echo $datacollection[2]['imageurl'];?>)">
                        <div class="category-img">
                            <img src="<?php echo $datacollection[2]['imageurl'];?>" alt="<?php echo $datacollection[2]['name']?>"/>
                        </div>
                        <div class="category-title">
                            <a href="<?php echo $datacollection[2]['url'];?>"><h4 class="category-name"><?php echo wordwrap($datacollection[2]['name'] , 8, "<br>\n", false);?></h4></a>
                        </div>
                    </div>
                </div>
            <?php 
           // endif;?>
            

           

    

	</div>
</div>
<?php }else{
    foreach($categories as $category){ 
     $cat = $this->getCategorymodel($category->getId());
           
            $data['name'] = $cat->getName();
            $data['url'] = $cat->getUrl();
            $datacollection[] = $data;
    }
    ?>
	<ul class="footer links categories-links">

        <li>
            <a href="<?php echo $datacollection[1]['url'];?>">
                    <span><?php echo $datacollection[1]['name']; ?></span>
                </a>
        </li>
         <li>
            <a href="<?php echo $datacollection[3]['url'];?>">
                    <span><?php echo $datacollection[3]['name']; ?></span>
                </a>
        </li>
        <li>
            <a href="<?php echo $datacollection[0]['url'];?>">
                    <span><?php echo $datacollection[0]['name']; ?></span>
                </a>
        </li>
         <li>
            <a href="<?php echo $datacollection[2]['url'];?>">
                    <span><?php echo $datacollection[2]['name']; ?></span>
                </a>
        </li>
	<?php
        //foreach($categories as $category):
          //  $cat = $this->getCategorymodel($category->getId());
        ?>
			<!-- li>
				<a href="<?php //echo $cat->getUrl(); ?>">
					<span><?php //echo $cat->getName(); ?></span>
				</a>
			</li> -->

    <?php //endforeach; ?>
	</ul>
<?php } ?>

<?php /*<div class="widget block block-static-block cwiw" id="catewithimg">
    <div class="block-content">
        <div class="content-heading">
            <h2 class="title"><?php echo $this->getMainTitle(); ?></h2>
            <p class="info"><?php echo $this->getTagLine(); ?></p>
        </div>
        <div class="row">
        <?php
        foreach($categories as $category):
            $cat = $this->getCategorymodel($category->getId());
            $image = $cat->getImageUrl();
        ?>
            <?php if($image != null): ?>
                <div class="col-md-4">
                    <a class="category_name" href="<?php echo $cat->getUrl(); ?>">
                       <img src="<?php echo $image; ?>" class="img-responsive category_image" alt="<?php echo $cat->getName(); ?>" />
                        <h3><span><?php echo $cat->getName(); ?></span></h3>
                    </a>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
        </div>
    </div>
</div>*/?>
