<div class="customer_info_container">
	<div class="customer-description">
		<h3>Hello, <?php   $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
			$customerSession = $objectManager->create('Magento\Customer\Model\Session');
		   if ($customerSession->isLoggedIn()) {
				$id= $customerSession->getCustomerId();  // get Customer Id
				$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
				$customerSession = $objectManager->create('Magento\Customer\Model\Customer')->load($id);
				echo $customerSession->getName();
			}
	?>!</h3>
		<p>From your my account dashboard you have the ability to view a snapshot of your recent activity and update your account information. Select a link below to view or edit information.</p>
	</div>
</div>