<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Sales\Block\Order\Info */ ?>
<?php //$_order = $block->getOrder() ?>

<!--
<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?php /* @escapeNotVerified */ //echo __('Order Information') ?></strong>
    </div>
    <div class="block-content">
    <?php //if (!$_order->getIsVirtual()): ?>
        <div class="box box-order-shipping-address">
            <strong class="box-title"><span><?php /* @escapeNotVerified */ //echo __('Shipping Address') ?></span></strong>
            <div class="box-content">
                <address><?php /* @escapeNotVerified */ //echo $block->getFormattedAddress($_order->getShippingAddress()); ?></address>
            </div>
        </div>

        <div class="box box-order-shipping-method">
            <strong class="box-title">
                <span><?php /* @escapeNotVerified */ //echo __('Shipping Method') ?></span>
            </strong>
            <div class="box-content">
            <?php //if ($_order->getShippingDescription()): ?>
                <?php //echo $block->escapeHtml($_order->getShippingDescription()) ?>
            <?php //else: ?>
                <?php /* @escapeNotVerified */ //echo __('No shipping information available'); ?>
            <?php //endif; ?>
            </div>
        </div>
    <?php //endif; ?>

        <div class="box box-order-billing-address">
            <strong class="box-title">
                <span><?php /* @escapeNotVerified */ //echo __('Billing Address') ?></span>
            </strong>
            <div class="box-content">
                <address><?php /* @escapeNotVerified */ //echo $block->getFormattedAddress($_order->getBillingAddress()); ?></address>
            </div>
        </div>
        <div class="box box-order-billing-method">
            <strong class="box-title">
                <span><?php /* @escapeNotVerified */ //echo __('Payment Method') ?></span>
            </strong>
            <div class="box-content">
                <?php //echo $block->getPaymentInfoHtml() ?>
            </div>
        </div>
    </div>
</div>
-->

<!--*****************************************************-->
<!-- Please Remove top coommented code After integration -->

<div class="col-lg-12 col-xs-12 shipping-details-container section-container">
	<div class="row">
		<div class="shipping-details">
			<div class="col-lg-12 col-xs-12 shipping-labels">
				<span class="order">2 SHIPMENTS </span>
			</div>
			<div class="col-lg-12 col-xs-12 shipping-content first">
				<div class="row">
					<div class="order-content">
						<div class="col-lg-12 col-xs-12">
							<div class="row">
								<div class="order-date col-lg-2 col-sm-4 col-md-3 col-xs-6">
									<span class="lite-text">
										Order date
									</span><br>
									<span class="clear-text">
										29 Oct 2017
									</span>
								</div>
								<div class="order-date col-lg-2 col-sm-4 col-md-3 col-xs-6">
									<span class="lite-text">
										Delivery
									</span><br>
									<span class="clear-text green">
										delivered to gatekepper
									</span>
								</div>
								
								<div class="order-date col-lg-1 col-sm-4 col-md-3 col-xs-6">
									<span class="lite-text">
										Total
									</span><br>
									<span class="clear-text">
										Rs.2000
									</span>
								</div>
								
								<div class="order-date col-lg-1 col-sm-4 col-md-3 col-xs-6">
									<span class="lite-text">
										Ship to
									</span><br>
									<span class="ordered-customer-name">
										Mankesh
									</span>
								</div>
								
							</div>
						</div>
						
						<div class="col-lg-12 col-xs-12">
							<div class="row">
								<div class="order-details-content table">
									<div class="col-lg-2 col-sm-4 col-md-3  col-xs-12 table-cell">
										<div class="product-image">
											<img src="<?php echo $this->getViewFileUrl('images/product.jpg');?>">
										</div>
									</div>
									<div class="col-lg-5 col-md-5 col-xs-12 table-cell">
										<span class="clear-text product-name">
											The Trabola
										</span><br>
										<span class="lite-text">
											Order Summary Order SummaryOrder SummaryOrder Summary
											Order SummaryOrder SummaryOrder SummaryOrder Summary
										</span>
									</div>
									<div class="col-lg-5 col-xs-12 table-cell">
										<div class="action">
											<div class="button-container">
												<button class="track" type="button">Track Order</button>
											</div>
											<div class="button-container">
												<button class="review" type="button">write a review</button>
											</div>
											<div class="button-container">
												<button class="return" type="button">cancel or return order</button>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			
			
			<div class="col-lg-12 col-xs-12 shipping-content">
				<div class="row">
					<div class="order-content">
						<div class="col-lg-12 col-xs-12">
							<div class="row">
								<div class="order-date col-lg-2 col-sm-4 col-md-3 col-xs-6">
									<span class="lite-text">
										Order date
									</span><br>
									<span class="clear-text">
										29 Oct 2017
									</span>
								</div>
								<div class="order-date col-lg-2 col-sm-4 col-md-3 col-xs-6">
									<span class="lite-text">
										Delivery
									</span><br>
									<span class="clear-text green">
										delivered to gatekepper
									</span>
								</div>
								
								<div class="order-date col-lg-1 col-sm-4 col-md-3 col-xs-6">
									<span class="lite-text">
										Total
									</span><br>
									<span class="clear-text">
										Rs.2000
									</span>
								</div>
								
								<div class="order-date col-lg-1 col-sm-4 col-md-3 col-xs-6">
									<span class="lite-text">
										Ship to
									</span><br>
									<span class="ordered-customer-name">
										Mankesh
									</span>
								</div>
								
							</div>
						</div>
						
						<div class="col-lg-12 col-xs-12">
							<div class="row">
								<div class="order-details-content table">
									<div class="col-lg-2 col-sm-4 col-md-3  col-xs-12 table-cell">
										<div class="product-image">
											<img src="<?php echo $this->getViewFileUrl('images/product.jpg');?>">
										</div>
									</div>
									<div class="col-lg-5 col-md-5 col-xs-12 table-cell">
										<span class="clear-text product-name">
											The Trabola
										</span><br>
										<span class="lite-text">
											Order Summary Order SummaryOrder SummaryOrder Summary
											Order SummaryOrder SummaryOrder SummaryOrder Summary
										</span>
									</div>
									<div class="col-lg-5 col-xs-12 table-cell">
										<div class="action">
											<div class="button-container">
												<button class="track" type="button">Track Order</button>
											</div>
											<div class="button-container">
												<button class="review" type="button">write a review</button>
											</div>
											<div class="button-container">
												<button class="return" type="button">cancel or return order</button>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

