<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php  /**@var $block \Magento\Sales\Block\Order\Info */ ?>
<?php $_order = $block->getOrder(); 
$items = $_order->getAllItems();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$myBlock = \Magento\Framework\App\ObjectManager::getInstance()->get('Mageplaza\Currentproduct\Block\Currentproduct');
$orderDetail = $objectManager->create('Magento\Sales\Model\Order')->load(14);
$value['qty_ordered'] = 1;
if ($orderDetail->canCancel()) {
    $orderItems = $orderDetail->getAllItems();        
    foreach ($orderItems as $value) {
    	echo $value['product_id'];
        if($value['product_id']==55)
        {    
            //$value->isDeleted(true);
            //$value->save();  

        }
        else
        {
         continue;
        }
    }
    //$orderDetail->save();
}

?>

<div class="col-lg-12 col-xs-12 shipping-details-container section-container">
	<div class="row">
		<div class="shipping-details">
			<div class="col-lg-12 col-xs-12 shipping-labels">
				<span class="order"><?php echo count($items);?> SHIPMENTS </span>
			</div>

			<?php foreach($items as $item) {
				$product = $item->getProduct();?>
				
			<div class="col-lg-12 col-xs-12 shipping-content first">
				<div class="row">
					<div class="order-content">
						<div class="col-lg-12 col-xs-12">
							<div class="row">
								<div class="order-date col-lg-2 col-sm-4 col-md-3 col-xs-6">
									<span class="lite-text">
										Order date
									</span><br>
									<span class="clear-text">
									<?php echo $_order->getCreatedAt(); ?>
									</span>
								</div>
								<div class="order-date col-lg-2 col-sm-4 col-md-3 col-xs-6">
									<span class="lite-text">
										Delivery
									</span><br>
									<span class="clear-text green">
										delivered to gatekepper
									</span>
								</div>
								
								<div class="order-date col-lg-1 col-sm-4 col-md-3 col-xs-6">
									<span class="lite-text">
										Total
									</span><br>
									<span class="clear-text">
										<?php echo $_order->getSubtotal();?>
									</span>
								</div>
								
								<div class="order-date col-lg-1 col-sm-4 col-md-3 col-xs-6">
									<span class="lite-text">
										Ship to
									</span><br>
									<span class="ordered-customer-name">
										<?php echo $_order->getCustomerName(); ?>
									</span>
								</div>
								
							</div>
						</div>
						
						<div class="col-lg-12 col-xs-12">
							<div class="row">
								<div class="order-details-content table">
									<div class="col-lg-2 col-sm-4 col-md-3  col-xs-12 table-cell">
										<div class="product-image">
											<img src="<?php echo $this->getViewFileUrl('images/product.jpg');?>">
										</div>
									</div>
									<div class="col-lg-5 col-md-5 col-xs-12 table-cell">
										<span class="clear-text product-name">
											<?php echo $product->getName();?>
										</span><br>
										<span class="lite-text">
											<?php $productbysku = $myBlock->getProductBySku($product->getSku());
											echo $productbysku->getData('short_description');
											?>
										
										</span>
									</div>
									<div class="col-lg-5 col-xs-12 table-cell">
										<div class="action">
											<div class="button-container">
												<button class="track" type="button">Track Order</button>
											</div>
											<div class="button-container">
												<button class="review" type="button">write a review</button>
											</div>
											<div class="button-container">
												<button class="return" onclick="location.href = 'https://next.desiredesire.com/cancel/index/index';">cancel or return order</button>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
	
	<?php }?>
	
		</div>
	</div>
</div>
