<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var  $block \Magento\Sales\Block\Order\View*/?>
<!--
<div class="order-details-items ordered">-->
    <?php $_order = $block->getOrder(); 
    
     ?>
<!--
    <div class="order-title">
        <strong><?php /* @escapeNotVerified */// echo __('Items Ordered') ?></strong>
        <?php// if ($_order->getTracksCollection()->count()) : ?>
            <?php //echo $block->getChildHtml('tracking-info-link') ?>
        <?php //endif; ?>
    </div>

    <?php //echo $block->getChildHtml('order_items') ?>

    <?php //if ($this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order', $_order) && $_order->getGiftMessageId()): ?>
    <div class="block block-order-details-gift-message">
        <div class="block-title"><strong><?php /* @escapeNotVerified */ //echo __('Gift Message for This Order') ?></strong></div>
        <?php //$_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessageForEntity($_order); ?>
        <div class="block-content">
            <dl class="item-options">
                <dt class="item-sender"><strong class="label"><?php /* @escapeNotVerified */ //echo __('From') ?></strong><?php //echo $block->escapeHtml($_giftMessage->getSender()) ?></dt>
                <dt class="item-recipient"><strong class="label"><?php /* @escapeNotVerified */ //echo __('To') ?></strong><?php //echo $block->escapeHtml($_giftMessage->getRecipient()) ?></dt>
                <dd class="item-message"><?php /* @escapeNotVerified */ //echo $this->helper('Magento\GiftMessage\Helper\Message')->getEscapedGiftMessage($_order) ?></dd>
            </dl>
        </div>
    </div>
    <?php //endif; ?>

    <div class="actions-toolbar">
        <div class="secondary">
            <a class="action back" href="<?php /* @escapeNotVerified */// echo $block->getBackUrl() ?>">
                <span><?php /* @escapeNotVerified */ //echo $block->getBackTitle() ?></span>
            </a>
        </div>
    </div>
</div>
-->

<!-- Please Remove Top Commented code After integration -->

<div class="col-lg-12 col-xs-12 order-details-container section-container">
	<div class="row">
		<div class="order-details">
			<div class="col-lg-12 col-xs-12 order-row">
				<div class="row">
					<div class="col-lg-6 col-xs-6 a-left">
						<div class="row">
							<span class="order"><?php 
							echo 'Order #'.$_order->getIncrementId().'';?></span>
						</div>
					</div>
					<div class="col-lg-6 col-xs-6 a-right">
						<div class="row">
							<span class="invoice">invoice</span>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-12 col-xs-12">
				<div class="row">
					<div class="order-content">
						<div class="col-lg-12 col-xs-12">
							<div class="row">
								<div class="order-date col-lg-2 col-sm-4 col-md-3 col-xs-6">
									<span class="lite-text">
										Order date
									</span><br>
									<span class="clear-text">
										<?php echo $_order->getCreatedAt(); ?>
									</span>
								</div>
								<div class="order-date col-lg-2 col-sm-4 col-md-3 col-xs-6">
									<span class="lite-text">
										Delivery
									</span><br>
									<span class="clear-text">
										29 Oct 2017
									</span>
								</div>
							</div>
						</div>
						
						<div class="col-lg-12 col-xs-12">
							<div class="row">
								<div class="order-details-content">
									<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
											<span class="lite-text">
												Ship to
											</span><br>
											<span class="ordered-customer-name">
												<?php echo $_order->getCustomerName(); ?>
											</span><br>
											<span class="address">
											<?php  $ShippingAddressobj = $_order->getShippingAddress();
											$ShippingAddress = $ShippingAddressobj->getData();
											echo $ShippingAddress['street'];echo"</br>";
											echo $ShippingAddress['city'];echo"</br>";
											echo $ShippingAddress['email'];echo"</br>";
											echo $ShippingAddress['postcode'];echo"</br>";
											echo $ShippingAddress['telephone'];
											?><br>
											</span>
									</div>
									<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
											<span class="lite-text">
												Payment Method
											</span><br>
											<span class="clear-text">
											<?php $payment = $_order->getPayment();
											echo $payment->getMethodInstance()->getTitle();
											?>
											</span>
									</div>
									<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
										<span class="lite-text">
												Order Summary
											</span>
										<table class="order-summary-table">
											<tbody>
												<tr><td>Item(s) subtotal</td><td><?php echo $_order->getSubtotal();?></td></tr>
												<tr><td>Shipping</td><td><?php echo $_order->getShippingAmount();?></td></tr>
												<tr><td>Total</td><td><?php echo $_order->getGrandtotal();?></td></tr>
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
