<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var $block Magento\Wishlist\Block\Catalog\Product\ProductList\Item\AddTo\Wishlist */
?>
<?php if ($block->getWishlistHelper()->isAllow()): 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');

$om = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $om->create('Magento\Customer\Model\Session');
$arrOfProductIds=array();  
if($customerSession->isLoggedIn()) {
    
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    //Load product by product id
    $collection = $objectManager->create('Magento\Wishlist\Model\ResourceModel\Item\CollectionFactory')->create();
    //print_r($collection); exit();
    $collection->addCustomerIdFilter( $customerSession->getCustomer()->getId());
     foreach ($collection as $item) {
            $arrOfProductIds[] = $item->getProductId();
        } 
}
$currentProduct = json_decode($block->getAddToWishlistParams($block->getProduct()));
$currentProductId = $currentProduct->data->product;

if( !in_array($currentProductId, $arrOfProductIds)){
?>
   <a href="#"
  	   id="loginpopup"
       class="action towishlist"
       title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
       aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
       data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($block->getProduct()); ?>'
       data-action="add-to-wishlist"
       role="button">
        <span><i id="fillin" class="fa fa-heart-o" aria-hidden="true"></i></span>
    </a> 
 
<?php }else{?>

       <a href="#"
       id="loginpopup"
       class="action towishlist"
       title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
       aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
       data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($block->getProduct()); ?>'
       data-action="add-to-wishlist"
       role="button">
        <span><i id="fillin" class="fa fa-heart" aria-hidden="true"></i></span>
      </a> 

<?php }endif; ?>


<script>
require(['jquery', 'jquery/ui'], function($){ 

 $( document ).ready(function() {    
$("#popupskip").on("click", function(e){

	
    
    $("#product-addtogroup-button").click();
    });
});
 
 });

</script>