<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<div id="checkout" data-bind="scope:'checkout'" class="checkout-container">
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
                 alt="<?php /* @escapeNotVerified */ echo __('Loading...'); ?>"
                 style="position: absolute;">
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
            }
        }
    </script>
    <script>
        window.checkoutConfig = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getCheckoutConfig()); ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
    </script>
    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>");
            return url.setBaseUrl('<?php /* @escapeNotVerified */ echo $block->getBaseUrl();?>');
        })
    </script>
</div>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
if(!$customerSession->isLoggedIn()) {
?>
<input type="hidden" id="log_act" value="no">
<script>
require([ 'jquery', 'jquery/ui'], function($){
 $( document ).ready(function() {
 function showpanel() { 
    jQuery("#social-login-popup").removeClass("mfp-hide");
	jQuery("#checkout-loader").css("display","none");
	
 }
 setTimeout(showpanel, 3000)
   });
})
</script>
<style>
.loading-mask{
background:none !important;
}
#custom-social {
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 1042;
    overflow: hidden;
    position: fixed;
    background: #fff;
    opacity: 0.95;
}
#social-login-popup{
    margin: 5% auto 0;
}
.white-popup {
    position: relative;
    background: #FFF;
    padding: 0;
    width: auto;
    /*max-width: 600px;
    margin: 30px auto 0;*/
}
/*#custom-social .fieldset > .field > .label{margin:0;}
#custom-social .fieldset > .field{margin:0 0 10px;}
#custom-social input[type="text"], #social-form-create input[type="password"], #social-form-create input[type="url"], #social-form-create input[type="tel"], #social-form-create input[type="search"], #social-form-create input[type="number"], #social-form-create input[type="datetime"], #social-form-create input[type="email"]{
height:25px;
}
#custom-social #social-login-popup .fieldset {
    margin: 0 0 10px;
}*/
</style>
<?php
}else{
 ?>
 <input type="hidden" id="log-act" value="yes">
<?php } ?>
    <?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $bse = $storeManager->getStore()->getBaseUrl();
    ?>
<input type="hidden" id="baseurl" value="<?php echo $bse; ?>">
