<div class="may-like-slider">
	<div class="maylike-heading">You may also like</div>
	<div class="owl-carousel-loaded owl-theme">
		<div class="item">
			<a href="#" title="" class="slider-product-image">
				<img class="lazyOwl" alt="" style="display: inline;" src="<?php echo $this->getViewFileUrl('Magento_Catalog::images/product_thumbnail_img.jpg');?>">
			</a>
			<h3 class="product-name">
				<a href="#" title="">VolksWagen 'Hipple' Camper</a>
			</h3>
			<div class="price-box">
				<p class="special-price">
					<span class="price color-red">
						<span class="CurrencySymbol">₹</span>18,968
					</span>
				</p>
			</div>
		</div>
		<div class="item">
			<a href="#" title="" class="slider-product-image">
				<img class="lazyOwl" alt="" style="display: inline;" src="<?php echo $this->getViewFileUrl('Magento_Catalog::images/product_thumbnail_img.jpg');?>">
			</a>
			<h3 class="product-name">
				<a href="#" title="">VolksWagen 'Hipple' Camper</a>
			</h3>
			<div class="price-box">
				<p class="special-price">
					<span class="price color-red">
						<span class="CurrencySymbol">₹</span>18,968
					</span>
				</p>
			</div>
		</div>
		<div class="item">
			<a href="#" title="" class="slider-product-image">
				<img class="lazyOwl" alt="" style="display: inline;" src="<?php echo $this->getViewFileUrl('Magento_Catalog::images/product_thumbnail_img.jpg');?>">
			</a>
			<h3 class="product-name">
				<a href="#" title="">VolksWagen 'Hipple' Camper</a>
			</h3>
			<div class="price-box">
				<p class="special-price">
					<span class="price color-red">
						<span class="CurrencySymbol">₹</span>18,968
					</span>
				</p>
			</div>
		</div>
		<div class="item">
			<a href="#" title="" class="slider-product-image">
				<img class="lazyOwl" alt="" style="display: inline;" src="<?php echo $this->getViewFileUrl('Magento_Catalog::images/product_thumbnail_img.jpg');?>">
			</a>
			<h3 class="product-name">
				<a href="#" title="">VolksWagen 'Hipple' Camper</a>
			</h3>
			<div class="price-box">
				<p class="special-price">
					<span class="price color-red">
						<span class="CurrencySymbol">₹</span>18,968
					</span>
				</p>
			</div>
		</div>
		<div class="item">
			<a href="#" title="" class="slider-product-image">
				<img class="lazyOwl" alt="" style="display: inline;" src="<?php echo $this->getViewFileUrl('Magento_Catalog::images/product_thumbnail_img.jpg');?>">
			</a>
			<h3 class="product-name">
				<a href="#" title="">VolksWagen 'Hipple' Camper</a>
			</h3>
			<div class="price-box">
				<p class="special-price">
					<span class="price color-red">
						<span class="CurrencySymbol">₹</span>18,968
					</span>
				</p>
			</div>
		</div>
		<div class="item">
			<a href="#" title="" class="slider-product-image">
				<img class="lazyOwl" alt="" style="display: inline;" src="<?php echo $this->getViewFileUrl('Magento_Catalog::images/product_thumbnail_img.jpg');?>">
			</a>
			<h3 class="product-name">
				<a href="#" title="">VolksWagen 'Hipple' Camper</a>
			</h3>
			<div class="price-box">
				<p class="special-price">
					<span class="price color-red">
						<span class="CurrencySymbol">₹</span>18,968
					</span>
				</p>
			</div>
		</div>
		<div class="item">
			<a href="#" title="" class="slider-product-image">
				<img class="lazyOwl" alt="" style="display: inline;" src="<?php echo $this->getViewFileUrl('Magento_Catalog::images/product_thumbnail_img.jpg');?>">
			</a>
			<h3 class="product-name">
				<a href="#" title="">VolksWagen 'Hipple' Camper</a>
			</h3>
			<div class="price-box">
				<p class="special-price">
					<span class="price color-red">
						<span class="CurrencySymbol">₹</span>18,968
					</span>
				</p>
			</div>
		</div>
		<div class="item">
			<a href="#" title="" class="slider-product-image">
				<img class="lazyOwl" alt="" style="display: inline;" src="<?php echo $this->getViewFileUrl('Magento_Catalog::images/product_thumbnail_img.jpg');?>">
			</a>
			<h3 class="product-name">
				<a href="#" title="">VolksWagen 'Hipple' Camper</a>
			</h3>
			<div class="price-box">
				<p class="special-price">
					<span class="price color-red">
						<span class="CurrencySymbol">₹</span>18,968
					</span>
				</p>
			</div>
		</div>
		<div class="item">
			<a href="#" title="" class="slider-product-image">
				<img class="lazyOwl" alt="" style="display: inline;" src="<?php echo $this->getViewFileUrl('Magento_Catalog::images/product_thumbnail_img.jpg');?>">
			</a>
			<h3 class="product-name">
				<a href="#" title="">VolksWagen 'Hipple' Camper</a>
			</h3>
			<div class="price-box">
				<p class="special-price">
					<span class="price color-red">
						<span class="CurrencySymbol">₹</span>18,968
					</span>
				</p>
			</div>
		</div>
		<div class="item">
			<a href="#" title="" class="slider-product-image">
				<img class="lazyOwl" alt="" style="display: inline;" src="<?php echo $this->getViewFileUrl('Magento_Catalog::images/product_thumbnail_img.jpg');?>">
			</a>
			<h3 class="product-name">
				<a href="#" title="">VolksWagen 'Hipple' Camper</a>
			</h3>
			<div class="price-box">
				<p class="special-price">
					<span class="price color-red">
						<span class="CurrencySymbol">₹</span>18,968
					</span>
				</p>
			</div>
		</div>
	</div>
</div>
<script>
require(['jquery','owl_carousel'],function($){
	$(document).ready(function() {
	  $('.owl-carousel-loaded').owlCarousel({
		loop: true,
		margin: 10,
		responsiveClass: true,
		responsive: {
		  0: {
			items: 2,
			nav: true
		  },
		  600: {
			items: 3,
			nav: false
		  },
		  1000: {
			items: 5,
			nav: true,
			loop: false,
			margin: 20
		  }
		}
	  })
	})
})
</script>