<div class="product-show-details-container">
	<div class="container">
		<h2>Details</h2>
		<div class="product-show-details-image">
			<img alt="" style="display: inline;" src="<?php echo $this->getViewFileUrl('Magento_Catalog::images/product-show-detial-1.png');?>">
		</div>
		<div class="row product-show-details-row">
			<div class="col-md-6">
				<h3>The Brand Story</h3>
				<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
				Lorem ipsum dolor sit amet, cons ectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
				<a class="product-show-read" href="#">Read More</a>
				<a class="product-show-cart" href="#">Add to bag</a>
			</div>
			<div class="col-md-6">
				<img alt="" style="display: inline;" src="<?php echo $this->getViewFileUrl('Magento_Catalog::images/product-show-detial-2.png');?>">
			</div>
		</div>
		<div class="row product-show-details-row">
			<div class="col-md-6">
				<img alt="" style="display: inline;" src="<?php echo $this->getViewFileUrl('Magento_Catalog::images/product-show-detial-3.png');?>">
			</div>
			<div class="col-md-6">
				<h3>The Craft</h3>
				<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
				Lorem ipsum dolor sit amet, cons ectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut </p>
				<a class="product-show-read" href="#">Read More</a>
				<a class="product-show-cart" href="#">Add to bag</a>
			</div>
		</div>
	</div>
</div>