<div class="product_specification">
	<div class="specificason-data">
		<div class="specification_data col-lg-6 col-md-6 col-sm-6 col-xs-12">
			<div class="specification-hed">
				<span class="specific-img"><img src="<?php echo $this->getViewFileUrl('Magento_Catalog::images/specific-img.jpg');?>" alt=""></span>
				<h6>Specifications</h6>
			</div>
			<ul>
				<li>World's first furtive civilian drone</li>
				<li>Unique sensory experience - files and flaps like a bird</li>
				<li>Resistant foam body, carbon fiber wings</li>
				<li>World's first furtive civilian drone</li>
				<li>Unique sensory experience - files and flaps like a bird</li>
				<li>Resistant foam body, carbon fiber wings</li>
				<li>World's first furtive civilian drone</li>
				<li>Unique sensory experience - files and flaps like a bird</li>
				<li>Resistant foam body, carbon fiber wings</li>
				<li>World's first furtive civilian drone</li>
				<li>Unique sensory experience - files and flaps like a bird</li>
				<li>Resistant foam body, carbon fiber wings</li>
				<li>World's first furtive civilian drone</li>
			</ul>
		</div>
		<div class="details_data col-lg-6 col-md-6 col-sm-6 col-xs-12">
			<div class="specification-hed">
				<span class="detail-img"><img src="<?php echo $this->getViewFileUrl('Magento_Catalog::images/detail-img.jpg');?>" alt=""></span>
				<h6>Details</h6>
			</div>
			<ul>
				<li><span>Size: </span>36.5 x 21 x 7.5 cm</li>
				<li><span>Weight: </span>8.35 g</li>
				<li><span>Capability: </span>All iOS and Android devices bluetooth 4.0</li>
				<li>In the box:
					<ul class="sub-ul">
						<li>Resistant foam body, carbon fiber wings</li>
						<li>Resistant foam body, carbon fiber wings</li>
						<li>Resistant foam body, carbon fiber wings</li>
						<li>Resistant foam body, carbon fiber wings</li>
						<li>Resistant foam body, carbon fiber wings</li>
						<li>Resistant foam body, carbon fiber wings</li>
					</ul>
				</li>
			</ul>
		</div>
	</div>
</div>