<div class="container-fluid product-show-video-container">
	<div class="container">
		<div class="row">
			<div class="col-md-6">
				<div class="product-show-video">
					<img alt="" style="display: inline;" src="<?php echo $this->getViewFileUrl('Magento_Catalog::images/product-show-video-img.jpg');?>">
					<a href="#">Watch it yourself <i class="fa fa-caret-right" aria-hidden="true"></i></a>
					</div>
			</div>
			<div class="col-md-6">
				<img alt="" style="display: inline;" src="<?php echo $this->getViewFileUrl('Magento_Catalog::images/product-show-video-img-2.jpg');?>">
			</div>
		</div>
	</div>
</div>