<?php /* ?>
<div class="may-like-slider-2">
	<div class="owl-carousel owl-theme">
		<div class="item">
			<a href="#" title="" class="slider-product-image">
				<img class="lazyOwl" alt="" style="display: inline;" src="<?php echo $this->getViewFileUrl('images/carousal-1.jpg');?>">
			</a>
			<div class="social_share_wish">
				<div class="social_wish_icon actions-secondary">
					<a href="#" class="action towishlist" title="Add to Wish List">
						<span><i class="fa fa-heart-o" aria-hidden="true"></i></span>
					</a>
				</div>
			</div>
		</div>
		<div class="item">
			<a href="#" title="" class="slider-product-image">
				<img class="lazyOwl" alt="" style="display: inline;" src="<?php echo $this->getViewFileUrl('images/carousal-2.jpg');?>">
			</a>
			<div class="social_share_wish">
				<div class="social_wish_icon actions-secondary">
					<a href="#" class="action towishlist" title="Add to Wish List">
						<span><i class="fa fa-heart-o" aria-hidden="true"></i></span>
					</a>
				</div>
			</div>
		</div>
		<div class="item">
			<a href="#" title="" class="slider-product-image">
				<img class="lazyOwl" alt="" style="display: inline;" src="<?php echo $this->getViewFileUrl('images/carousal-1.jpg');?>">
			</a>
			<div class="social_share_wish">
				<div class="social_wish_icon actions-secondary">
					<a href="#" class="action towishlist" title="Add to Wish List">
						<span><i class="fa fa-heart-o" aria-hidden="true"></i></span>
					</a>
				</div>
			</div>
		</div>
		<div class="item">
			<a href="#" title="" class="slider-product-image">
				<img class="lazyOwl" alt="" style="display: inline;" src="<?php echo $this->getViewFileUrl('images/carousal-2.jpg');?>">
			</a>
			<div class="social_share_wish">
				<div class="social_wish_icon actions-secondary">
					<a href="#" class="action towishlist" title="Add to Wish List">
						<span><i class="fa fa-heart-o" aria-hidden="true"></i></span>
					</a>
				</div>
			</div>
		</div>
		<div class="item">
			<a href="#" title="" class="slider-product-image">
				<img class="lazyOwl" alt="" style="display: inline;" src="<?php echo $this->getViewFileUrl('images/carousal-1.jpg');?>">
			</a>
			<div class="social_share_wish">
				<div class="social_wish_icon actions-secondary">
					<a href="#" class="action towishlist" title="Add to Wish List">
						<span><i class="fa fa-heart-o" aria-hidden="true"></i></span>
					</a>
				</div>
			</div>
		</div>
		<div class="item">
			<a href="#" title="" class="slider-product-image">
				<img class="lazyOwl" alt="" style="display: inline;" src="<?php echo $this->getViewFileUrl('images/carousal-2.jpg');?>">
			</a>
			<div class="social_share_wish">
				<div class="social_wish_icon actions-secondary">
					<a href="#" class="action towishlist" title="Add to Wish List">
						<span><i class="fa fa-heart-o" aria-hidden="true"></i></span>
					</a>
				</div>
			</div>
		</div>
		<div class="item">
			<a href="#" title="" class="slider-product-image">
				<img class="lazyOwl" alt="" style="display: inline;" src="<?php echo $this->getViewFileUrl('images/carousal-1.jpg');?>">
			</a>
			<div class="social_share_wish">
				<div class="social_wish_icon actions-secondary">
					<a href="#" class="action towishlist" title="Add to Wish List">
						<span><i class="fa fa-heart-o" aria-hidden="true"></i></span>
					</a>
				</div>
			</div>
		</div>
		<div class="item">
			<a href="#" title="" class="slider-product-image">
				<img class="lazyOwl" alt="" style="display: inline;" src="<?php echo $this->getViewFileUrl('images/carousal-2.jpg');?>">
			</a>
			<div class="social_share_wish">
				<div class="social_wish_icon actions-secondary">
					<a href="#" class="action towishlist" title="Add to Wish List">
						<span><i class="fa fa-heart-o" aria-hidden="true"></i></span>
					</a>
				</div>
			</div>
		</div>
		<div class="item">
			<a href="#" title="" class="slider-product-image">
				<img class="lazyOwl" alt="" style="display: inline;" src="<?php echo $this->getViewFileUrl('images/carousal-1.jpg');?>">
			</a>
			<div class="social_share_wish">
				<div class="social_wish_icon actions-secondary">
					<a href="#" class="action towishlist" title="Add to Wish List">
						<span><i class="fa fa-heart-o" aria-hidden="true"></i></span>
					</a>
				</div>
			</div>
		</div>
		<div class="item">
			<a href="#" title="" class="slider-product-image">
				<img class="lazyOwl" alt="" style="display: inline;" src="<?php echo $this->getViewFileUrl('images/carousal-2.jpg');?>">
			</a>
			<div class="social_share_wish">
				<div class="social_wish_icon actions-secondary">
					<a href="#" class="action towishlist" title="Add to Wish List">
						<span><i class="fa fa-heart-o" aria-hidden="true"></i></span>
					</a>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
require(['jquery','owl_carousel'],function($){
	$(document).ready(function() {
	  $('.may-like-slider-2 .owl-carousel').owlCarousel({
		loop: true,
		margin: 10,
		responsiveClass: true,
		stagePadding:50,
		responsive: {
		  0: {
			items: 3,
			nav: false
		  },
		  600: {
			items: 3,
			nav: false
		  },
		  1000: {
			items: 3,
			nav: false,
			stagePadding:100,
			margin: 15
		  }
		}
	  })
	})
});
</script>
<?php */ ?>
