<?php 
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance(); 
$productCollectionFactory = $objectManager->get('\Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');
$collection = $productCollectionFactory->create();
$collection->addAttributeToSelect('*');
$collection->addAttributeToFilter('collectors_edition', 1);
$collection->setPageSize(5); // selecting only 3 products

?>
<div class="collectores-edition section-cotainer"> 
	<div class="mobile-collectors" id="mobile-collectors">
		<div class="mobile-collectors-text">
			<div class="collector-box">
				<div class="collector-text">
					<h2 class="colletores-title">COLLECTOR'S EDITION</h2>
					<p class="sub-title">For the brave few who still believe that function is for computers and beauty is for mankind, salvation is here. Gentlemen and ladies, here are the curated few, from our curated best. <br/>Do indulge.</p> 
				</div>
			</div>
		</div>
		<div class="columns-grid grid-2" id="mobile-collectors-carousel">
			<?php foreach ($collection as $_product) { ?>
			<?php 
				$configMgr = $objectManager->get('Magento\ConfigurableProduct\Model\Product\Type\Configurable'); 
				$childProducts = $configMgr->getUsedProducts($_product,null);   
				$CountfirstChildProduct = 0 ;
				foreach($childProducts as $childProduct) {
					if($CountfirstChildProduct == 0){
						$firstChildProductId = $childProduct->getId();
					}
					$CountfirstChildProduct++;
				}
				if($_product->getTypeId() == 'configurable'){
					$productId = $firstChildProductId;
				}else{
					$productId = $_product->getId();
				}
			?>
			<?php 	
				$productdata = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId()); 
				$childProductOfConfig = $objectManager->create('Magento\Catalog\Model\Product')->load($productId);
			?>
			<?php $images = $productdata->getMediaGalleryImages(); ?>
			<?php
					$_imagehelper = $objectManager->get('\Magento\Catalog\Helper\Image');
					$lifestyle = $_imagehelper->init($productdata,'product_base_image')
										->setImageFile($productdata->getFile())
										->resize(640, 512)
										->getUrl();
			?>
			<div class="grid">
				<div class="collector-box">
					<div class="collector-img">
						<a href="<?php echo $productdata->getProductUrl(); ?>"><img src="<?php echo $lifestyle;?>" /></a>
					</div>
					<div class="collector-info">
						<div class="info-content a-center">
							<?php
								$product_name = strip_tags($_product->getName());

								if (strlen($product_name) > 30) {
								$stringCut = substr($product_name, 0, 30);
								$product_name = substr($stringCut, 0, strrpos($stringCut, ' ')).'...'; 
								}
							?>
					
						
							<span class="left"><?php echo $_product->getName();?></span>
							<span class="a-center red"><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($childProductOfConfig->getPrice(),true,false);?></span>
						</div>
					</div>
				</div>
			</div>
			<?php } ?>
		</div>
		<div class="explore-button">
			<a class="strong" href="<?php echo $this->getUrl('collectors-edition');?>">Explore All</a>
		</div>
	</div>
</div>
