<?php /*<!-- Shipping and fetured block--> */?>

<div class="footer-shipping-feture-container section-cotainer">
	<div class="footer-shipping-feture-content">
		<div class="columns-grid grid-4">
			<div class="grid">
				<div class="feture-content">
					<div class="icon-block">
						<img src="<?php echo $this->getViewFileUrl('images/shipping.jpg');?>"/>
					</div>
					<div class="feature-text">
						<strong class="feature-head">Shipping</strong><br/><span>free, across India</span>
					</div>
				</div>
			</div>
			<div class="grid">
				<div class="feture-content">
					<div class="icon-block">
						<img src="<?php echo $this->getViewFileUrl('images/clock.jpg');?>"/>
					</div>
					<div class="feature-text">
						<strong class="feature-head">Delivery</strong><br/><span>5-7 working days</span>
					</div>
				</div>
			</div>
			<div class="grid">
				<div class="feture-content">
					<div class="icon-block">
						<img src="<?php echo $this->getViewFileUrl('images/replace.jpg');?>"/>
					</div>
					<div class="feature-text">
						<strong class="feature-head">Replacement</strong><br/><span>15 days; no questions asked</span>
					</div>
				</div>
			</div>
			<div class="grid">
				<div class="feture-content">
					<div class="icon-block">
						<img src="<?php echo $this->getViewFileUrl('images/payment.jpg');?>"/>
					</div>
					<div class="feature-text">
						<strong class="feature-head">Payment</strong><br/><span>major credit/debit cards; COD</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>