<?php /*<!-- ************************* Testimonial Block ************************* --> */?>

<div class="testimonial-container section-cotainer">
	<div class="testimonial-content">
		<div class="testimonial-slider" id="testimonial-slider">
			<div class="items">
				<div class="testimonial-box">
					<div class="quote-icon">
						<img class="quote" src="<?php echo $this->getViewFileUrl('images/quote.jpg');?>">
					</div>
					<div class="testi_data">
						<div class="quote-content">
							<div class="quote-text">
								<span>"DesireDesire matches the vocabulary synonyms wish, want, longing, yearning, aspiration, fascination, inclination…. the list is long."</span>
							</div>
							<div class="quote-writer">
								<span class="writer">
									<a href="https://khizirjaffriblog.wordpress.com/2017/05/28/desire-of-all/">Khizir Jaffri</a>
								</span><br/>
								<span class="post-name">
									BLOGGER
								</span>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="items">
				<div class="testimonial-box">
					<div class="quote-icon">
						<img class="quote" src="<?php echo $this->getViewFileUrl('images/quote.jpg');?>">
					</div>
					<div class="testi_data">
						<div class="quote-content">
							<div class="quote-text">
								<span>"The general assurance of 7 days no question asked return policy makes it the winner for me. Even though the website does not have onsite demo, the customer care is very responsive on social media platforms as well as the number dedicated to customer service."</span>
							</div>
							<div class="quote-writer">
								<span class="writer">
									<a href="https://plumptopretty.blogspot.in/2017/05/the-girl-guide-to-tech-antiordinary.html">Neelakshi Singh</a>
								</span><br/>
								<span class="post-name">
									BLOGGER/CUSTOMER
								</span>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="items">
				<div class="testimonial-box">
					<div class="quote-icon">
						<img class="quote" src="<?php echo $this->getViewFileUrl('images/quote.jpg');?>">
					</div>
					<div class="testi_data">
						<div class="quote-content">
							<div class="quote-text">
								<span>"Super Slim, Exact Fit for my Iphone7! Unique collections of mobile phone cases. Definitely recommend, in fact I am going to get few more valentine collection for my girl. Well priced and arrived within stated delivery time from Desire Desire."</span>
							</div>
							<div class="quote-writer">
								<span class="writer">
									<a href="https://goo.gl/ZH5yyZ">Chandan Prabhakar</a>
								</span><br/>
								<span class="post-name">
									CUSTOMER
								</span>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="items">
				<div class="testimonial-box">
					<div class="quote-icon">
						<img class="quote" src="<?php echo $this->getViewFileUrl('images/quote.jpg');?>">
					</div>
					<div class="testi_data">
						<div class="quote-content">
							<div class="quote-text">
								<span>"I have ordered a Bluetooth key lock (via app) from desire desire for our main door. I have been using it for the last 3 months now and it works perfectly. We use it around 12-15 times a day. Easy to setup and any local carpentar can fix it for you. Good stuff team desire. Keep it up."</span>
							</div>
							<div class="quote-writer">
								<span class="writer">
									<a href="https://www.facebook.com/pg/Ivedesire/reviews/">Rahul Mansabdar</a>
								</span><br/>
								<span class="post-name">
									CUSTOMER
								</span>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="items">
				<div class="testimonial-box">
					<div class="quote-icon">
						<img class="quote" src="<?php echo $this->getViewFileUrl('images/quote.jpg');?>">
					</div>
					<div class="testi_data">
						<div class="quote-content">
							<div class="quote-text">
								<span>"Very rarely does a purchase decision come so close to gifting yourself ... this definitely does!"</span>
							</div>
							<div class="quote-writer">
								<span class="writer">
									<a href="https://www.facebook.com/pg/Ivedesire/reviews/">Samudra Sengupta</a>
								</span><br/>
								<span class="post-name">
									CUSTOMER
								</span>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="items">
				<div class="testimonial-box">
					<div class="quote-icon">
						<img class="quote" src="<?php echo $this->getViewFileUrl('images/quote.jpg');?>">
					</div>
					<div class="testi_data">
						<div class="quote-content">
							<div class="quote-text">
								<span>"I bought a ztylus case with lens for my iPhone 6s.The delivery was on time.The packing was great and they sent a letter of appreciation with it.Very thoughtful.Above all the product is great."</span>
							</div>
							<div class="quote-writer">
								<span class="writer">
									<a href="https://www.facebook.com/pg/Ivedesire/reviews/">Sudeep Ranjan Sarkar</a>
								</span><br/>
								<span class="post-name">
									CUSTOMER
								</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>