<?php /* <!--       Welcode Massege Box Start Here         --> */ ?>
<div id="stop-location"></div>
<div class="welcome-box-container" id="welcome-box-container">
	<div class="welcome-box">
		<div class="scroll-down">
			<a id="scroll-down-arrow" href="javascript:void(0)" onclick="smoothScroll(document.getElementById('stop-location'))">
				<img src="<?php echo $this->getViewFileUrl('images/scroll-down.png');?>" alt="scroll down"/>
			</a>
		</div>
		<div class="welcome-text" id="welcome-text">
			<p class="strong">Welcome to <span style="color:#ff685b">Desire Desire,</span><br/></p>
			For the aesthete, there’s no greater joy than appreciating beauty. Which is what makes Desire Desire an unending delight. With joyfully curated products that bring beauty and design to objects we use daily.<br/>Go ahead, surround yourself with the <span class="red">antiordinary</span>.
		</div>
	</div>
</div>

<?php /* <!--       Welcode Massege Box end Here         --> */ ?>