<!----------------   Carousel Products tab    ------------------>

<div class="tabs-container section-cotainer">
	<div class="tabs-content">
		<div class="tab">
		  <a class="tablinks active" onclick="openTab(event, 'bestseller')">Best Seller</a>
		  <a class="tablinks" onclick="openTab(event, 'featured')">Featured</a>
		  <a class="tablinks" onclick="openTab(event, 'popular')">Popular</a>
		</div>

		<div id="bestseller" class="tabcontent" style="display:block">
			<div class="bestseller-products-container">
				<div class="products-container" id="carousel">
					<div class="products-grid grid-3">
						<div class="items grid">
							<div class="product-content">
								<div class="product-image">
									<img src="<?php echo $this->getViewFileUrl('images/img-1.jpg');?>">
								</div>
								<div class="product-details">
									<h4 class="product-name">IPhone cases</h4>
									<span class="price">Rs. 20000 </span>
								</div>
								<div class="action">
									<button class="fill add-to-cart fixed left" onclick="#">Add to cart</button>
									<button class="view-more-button right fixed" onclick="#">Explore</button>
								</div>
							</div>
						</div>
						
						<div class="items grid">
							<div class="product-content">
								<div class="product-image">
									<img src="<?php echo $this->getViewFileUrl('images/img-1.jpg');?>">
								</div>
								<div class="product-details">
									<h4 class="product-name">IPhone cases</h4>
									<span class="price">Rs. 20000 </span>
								</div>
								<div class="action">
									<button class="fill add-to-cart fixed left" onclick="#">Add to cart</button>
									<button class="view-more-button right fixed" onclick="#">Explore</button>
								</div>
							</div>
						</div>
						
						<div class="items grid">
							<div class="product-content">
								<div class="product-image">
									<img src="<?php echo $this->getViewFileUrl('images/img-1.jpg');?>">
								</div>
								<div class="product-details">
									<h4 class="product-name">IPhone cases</h4>
									<span class="price">Rs. 20000 </span>
								</div>
								<div class="action">
									<button class="fill add-to-cart fixed left" onclick="#">Add to cart</button>
									<button class="view-more-button right fixed" onclick="#">Explore</button>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div id="featured" class="tabcontent">
			<div class="featured-products-container">
				<div class="products-container" id="carousel">
					<div class="products-grid grid-3">
						<div class="items grid">
							<div class="product-content">
								<div class="product-image">
									<img src="<?php echo $this->getViewFileUrl('images/img-3.jpg');?>">
								</div>
								<div class="product-details">
									<h4 class="product-name">IPhone cases</h4>
									<span class="price">Rs. 20000 </span>
								</div>
								<div class="action">
									<button class="fill add-to-cart fixed left" onclick="#">Add to cart</button>
									<button class="view-more-button right fixed" onclick="#">Explore</button>
								</div>
							</div>
						</div>
						
						<div class="items grid">
							<div class="product-content">
								<div class="product-image">
									<img src="<?php echo $this->getViewFileUrl('images/img-3.jpg');?>">
								</div>
								<div class="product-details">
									<h4 class="product-name">IPhone cases</h4>
									<span class="price">Rs. 20000 </span>
								</div>
								<div class="action">
									<button class="fill add-to-cart fixed left" onclick="#">Add to cart</button>
									<button class="view-more-button right fixed" onclick="#">Explore</button>
								</div>
							</div>
						</div>
						
						<div class="items grid">
							<div class="product-content">
								<div class="product-image">
									<img src="<?php echo $this->getViewFileUrl('images/img-3.jpg');?>">
								</div>
								<div class="product-details">
									<h4 class="product-name">IPhone cases</h4>
									<span class="price">Rs. 20000 </span>
								</div>
								<div class="action">
									<button class="fill add-to-cart fixed left" onclick="#">Add to cart</button>
									<button class="view-more-button right fixed" onclick="#">Explore</button>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div id="popular" class="tabcontent">
			<div class="featured-products-container">
				<div class="products-container" id="carousel">
					<div class="products-grid grid-3">
						<div class="items grid">
							<div class="product-content">
								<div class="product-image">
									<img src="<?php echo $this->getViewFileUrl('images/img-2.jpg');?>">
								</div>
								<div class="product-details">
									<h4 class="product-name">IPhone cases</h4>
									<span class="price">Rs. 20000 </span>
								</div>
								<div class="action">
									<button class="fill add-to-cart fixed left" onclick="#">Add to cart</button>
									<button class="view-more-button right fixed" onclick="#">Explore</button>
								</div>
							</div>
						</div>
						
						<div class="items grid">
							<div class="product-content">
								<div class="product-image">
									<img src="<?php echo $this->getViewFileUrl('images/img-2.jpg');?>">
								</div>
								<div class="product-details">
									<h4 class="product-name">IPhone cases</h4>
									<span class="price">Rs. 20000 </span>
								</div>
								<div class="action">
									<button class="fill add-to-cart fixed left" onclick="#">Add to cart</button>
									<button class="view-more-button right fixed" onclick="#">Explore</button>
								</div>
							</div>
						</div>
						
						<div class="items grid">
							<div class="product-content">
								<div class="product-image">
									<img src="<?php echo $this->getViewFileUrl('images/img-2.jpg');?>">
								</div>
								<div class="product-details">
									<h4 class="product-name">IPhone cases</h4>
									<span class="price">Rs. 20000 </span>
								</div>
								<div class="action">
									<button class="fill add-to-cart fixed left" onclick="#">Add to cart</button>
									<button class="view-more-button right fixed" onclick="#">Explore</button>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div> 
	</div>
</div>
