<!----------------   Carousel Products tab    ------------------>
<?php 
// $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
// $myBlock = \Magento\Framework\App\ObjectManager::getInstance()->get('Mageplaza\Currentproduct\Block\ProductCollection');
// $currentProduct = $myBlock->getProducts();
?>
<div class="tabs-container section-cotainer">
	<div class="tabs-content">
		<div class="tab">
		  <a class="tablinks active" onclick="openTab(event, 'bestseller')">Best Seller</a>
		  <a class="tablinks" onclick="openTab(event, 'featured')">New Products</a>
		  <a class="tablinks" onclick="openTab(event, 'popular')">Popular</a>
		</div>

		<div id="bestseller" class="tabcontent" style="display:block">
			<div class="bestseller-products-container">
				<div class="products-container" id="carousel">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('newproducts')->toHtml();?>
				</div>
			</div>
		</div>

		<div id="featured" class="tabcontent">
			<div class="featured-products-container">
				<div class="products-container" id="carousel">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('bestseller')->toHtml();?>
				</div>
			</div>
		</div>

		<div id="popular" class="tabcontent">
			<div class="featured-products-container">
				<div class="products-container" id="carousel">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('newproducts')->toHtml();?>
				</div>
			</div>
		</div>
	</div> 
</div>

