<script type="text/javascript" src="<?php echo $this->getViewFileUrl('js/custom.js'); ?>"></script>

<?php /*
<span class="scroll-top"><img src="<?php echo $this->getViewFileUrl('images/scroll-top.png') ?>"></span>
*/ ?>

<span class="footer-icons"> 
	<a href="https://www.facebook.com/Ivedesire"><img class="fb" title="Facebook" alt="Facebook" src="<?php echo $this->getViewFileUrl('images/facebook.png') ?>"></a>
	<a href="https://www.instagram.com/ivedesire"><img class="ins" title="Instagram" alt="Instagram" src="<?php echo $this->getViewFileUrl('images/instagram.png') ?>"></a>
	<a href="https://twitter.com/ivedesire"><img class="tw" title="Twitter" alt="Twitter" src="<?php echo $this->getViewFileUrl('images/twitter.png') ?>"></a>
	<a href="https://in.pinterest.com/ivedesire"><img class="tw" title="Pintrest" alt="Pintrest" src="<?php echo $this->getViewFileUrl('images/pinterest.png') ?>"></a>
	<a href="https://www.youtube.com/channel/UC9o5YNObRBm6FbIXE4fHc4A"><img class="tw" title="Youtube" alt="Youtube" src="<?php echo $this->getViewFileUrl('images/youtube.png') ?>"></a>
	<a href="https://www.linkedin.com/company/desire-desire"><img class="tw" title="Linkedin" alt="Linkedin" src="<?php echo $this->getViewFileUrl('images/linkedin.png') ?>"></a>
</span>

<script type="text/javascript">
/*	jQuery(document).ready(function () {
       jQuery(window).scroll(function () {
           if (jQuery(this).scrollTop() > 200) {
               jQuery('.scroll-top').fadeIn();
           } else {
               jQuery('.scroll-top').fadeOut();
           }
       });
       jQuery('.scroll-top').click(function () {
           jQuery("html, body").animate({
               scrollTop: 0
           }, 600);
           return false;
       });
   });
*/
</script>