<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>
<div class="block block-customer-login mobile-login-page">
    
    <div class="block-content" aria-labelledby="block-customer-login-heading">
		<div id="customer-login" class="customer-login" style="float:left;">
			<div class="social-login block-container authentication">
				<div class="social-login-title">
					<h3 class="login-title">Log in</h3>
					<p class="small-white">Good to see you back. Log in to access your Orders, Wishlist and recommendations.</p>
				</div>
				<div class="block social-login-customer-authentication col-mp mp-7" id="social-login-authentication">
					<div class="block-title">
						<h3 class="login-head">Log in</h3>
						<span id="otp-login" role="heading" aria-level="2">Log in with OTP</span>
						
					</div>
					<div class="block-content" aria-labelledby="block-customer-login-heading">
						<form class="form form-login" action="<?php echo $block->getPostActionUrl() ?>" method="post" id="login-form" data-mage-init='{"validation":{}}'>
						<?php echo $block->getBlockHtml('formkey'); ?>                
							<fieldset class="fieldset login">
								<div class="field email required">
									<div class="control">
										<input name="login[username]" placeholder="Email/Mobile Number" value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?php echo __('Email') ?>" data-validate="{required:true, 'validate-email':true}">
									</div>
								</div>
								<div class="field password required">
									<div class="control">
										<input name="login[password]" placeholder="Password" type="password" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?php echo __('Password') ?>" data-validate="{required:true}">
									</div>
								</div>
								<div class="actions-toolbar">
									<div class="primary">
										<button type="submit" class="action login primary" name="send" id="send2">
											<span><?php echo __('Log In') ?></span>
										</button>
									</div>
									<div class="secondary">
										<a class="action remind" href="<?php echo $block->getForgotPasswordUrl() ?>">
											<span><?php  echo __('Forgot Your Password?') ?></span>
										</a>
									</div>
								</div>
							</fieldset>
						</form>
					</div>
					<div class="custom-otp" style="display:none">
						<span id="back" class="right" role="heading" style="cursor:pointer;" aria-level="2">Back</span>
						<div class="form-customer-login" id="social-form-login">
							<fieldset class="fieldset login">
								<div class="field required">
									<div class="control">
										<input name="mobile" id="mobile1" type="text" class="input-text" title="Mobile" placeholder="Mobile">
										<span id="sent-success" class="fa fa-check" aria-hidden="true"></span>
									</div>
								</div>
								
								<div class="field otp required" style="display:none">
									<div class="control">
										<input name="otp" id="otp" type="text" class="input-text" value="" title="OTP" placeholder="CODE">
									</div>
									<span class="resend">Resend</span>
								</div>
								<div class="actions-toolbar width-100">
									<div class="primary">
										<button type="button" class="action disable" id="get-otp"><span>Get OTP</span></button>
										<button type="button" style="display:none" class="action" id="verify"><span>Verify</span></button>
										
										<span style="display:none" class="otp-msg not-exist">Number not registered !</span>
										<span style="display:none" class="otp-msg not-match">Enter correct OTP !</span>
										<span style="display:none" class="otp-msg logged">Logged in successfully !</span>
										<span style="display:none" class="otp-msg sent">OTP, sent.</span>
										<span style="display:none" class="otp-msg resent">OTP, resent.</span>
									</div>
								</div>
							</fieldset>
						</div>
					</div>
				</div>
			</div>
		</div>
    </div>
</div>
<script>
 require(['jquery'], function($){
	jQuery(document).ready(function(){
		jQuery(document).on('click','#otp-login',function(){
			$('.social-login-customer-authentication .block-content').hide();
			$('#otp-login').hide();
			$('.login-head').replaceWith('<h3 class="login-head">Login with OTP</h3>');
			$('.custom-otp').show();
		});
		
		jQuery(document).on('click','#back',function(){
			$('.social-login-customer-authentication .block-content').show();
			$('#otp-login').show();
			$('.custom-otp').hide();
			$('.login-head').replaceWith('<h3 class="login-head">Log in</h3>');
		});
	});
 });
 </script>