<div class="container-fluid">
	<div class="profile-left">
		<div class="profile-icon">
			<img src="<?php echo $this->getViewFileUrl('RI_Artist::images/profile-image.png');?>" alt="">
		</div>
		<div class="profile-description">
			<h3>Chris Fernadez</h3>
			<h4>Bangalore</h4>
			<p>Designer, illustrator, comic-reader.</p>
			<a href="#">Message</a>
		</div>
		<div class="profile-description-bottom">
			<h4>Skills</h4>
			<p>Illustration | Graphic Design | Typography</p>
			
		</div>
		<div class="profile-description-bottom-social">
			<img src="<?php echo $this->getViewFileUrl('RI_Artist::images/facebook-red.png');?>" alt="">
			<img src="<?php echo $this->getViewFileUrl('RI_Artist::images/instagram-red.png');?>" alt="">
			<img src="<?php echo $this->getViewFileUrl('RI_Artist::images/twitter-red.png');?>" alt="">
		</div>
	</div>
	<div class="profile-right">
		<h4>About</h4>
		<p>My name is Chris Fernandez and i am a graphic designer & photographer from Stockholm, Sweden. My work vary from making big artprints to designing various products. And Desire Desire have offered me the opportunity to come in contact with a whole new artistic culture in India wich i am really grateful and excited about. I mix my influences and styles quite extensively. I like to combine photography with different types of digital work and drawings and I am constantly trying to improve and learn new styles and techniques.</p>
	</div>
</div>