<div class="profile-product-container">
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<h3>Chris designs for <span>iPhone 6s  <i class="fa fa-angle-down" aria-hidden="true"></i></span></h3>
			<p>210 cases found</p>
		</div>
		<div class="artist_toolbar">
			<div class="category-sort-by">
				<div class="sort_options">
					<div class="sortby-label">Sort By:</div>
					<div class="shortby_opson">Price<span class="option-arrow"></span></div>
					<div class="shortby_opson">Popular<span class="option-arrow"></span></div>
				</div>
			</div>
		</div>
	</div>
	<div class="artist_design">
		<ul>
			<li class="col-lg-3 col-md-3 col-sm-4 col-xs-6 "> 
				<div class="design-info">
					<div class="art-img-wrapper">
						<a href="#" title="" class="art-img">
							<img src="<?php echo $this->getViewFileUrl('RI_Artist::images/similar-1.png');?>" alt="">
						</a>                
					</div> 
					<h5 class="design-name" style=""><a href="#" title="">VolksWagen 'Hipple' Camper</a></h5>
					<h6 class="design_sub_detail">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed</h6>
					<div class="price-box">
						<p class="special-price">
							<span class="price color-red">
								<span class="CurrencySymbol">₹</span>18,968
							</span>
						</p>
					</div>
				</div>
			</li>
			<li class="col-lg-3 col-md-3 col-sm-4 col-xs-6 "> 
				<div class="design-info">
					<div class="art-img-wrapper">
						<a href="#" title="" class="art-img">
							<img src="<?php echo $this->getViewFileUrl('RI_Artist::images/similar-1.png');?>" alt="">
						</a>                
					</div> 
					<h5 class="design-name" style=""><a href="#" title="">VolksWagen 'Hipple' Camper</a></h5>
					<h6 class="design_sub_detail">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed</h6>
					<div class="price-box">
						<p class="special-price">
							<span class="price color-red">
								<span class="CurrencySymbol">₹</span>18,968
							</span>
						</p>
					</div>
				</div>
			</li>
			<li class="col-lg-3 col-md-3 col-sm-4 col-xs-6 "> 
				<div class="design-info">
					<div class="art-img-wrapper">
						<a href="#" title="" class="art-img">
							<img src="<?php echo $this->getViewFileUrl('RI_Artist::images/similar-1.png');?>" alt="">
						</a>                
					</div> 
					<h5 class="design-name" style=""><a href="#" title="">VolksWagen 'Hipple' Camper</a></h5>
					<h6 class="design_sub_detail">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed</h6>
					<div class="price-box">
						<p class="special-price">
							<span class="price color-red">
								<span class="CurrencySymbol">₹</span>18,968
							</span>
						</p>
					</div>
				</div>
			</li>
			<li class="col-lg-3 col-md-3 col-sm-4 col-xs-6 "> 
				<div class="design-info">
					<div class="art-img-wrapper">
						<a href="#" title="" class="art-img">
							<img src="<?php echo $this->getViewFileUrl('RI_Artist::images/similar-1.png');?>" alt="">
						</a>                
					</div> 
					<h5 class="design-name" style=""><a href="#" title="">VolksWagen 'Hipple' Camper</a></h5>
					<h6 class="design_sub_detail">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed</h6>
					<div class="price-box">
						<p class="special-price">
							<span class="price color-red">
								<span class="CurrencySymbol">₹</span>18,968
							</span>
						</p>
					</div>
				</div>
			</li>
			<li class="col-lg-3 col-md-3 col-sm-4 col-xs-6 "> 
				<div class="design-info">
					<div class="art-img-wrapper">
						<a href="#" title="" class="art-img">
							<img src="<?php echo $this->getViewFileUrl('RI_Artist::images/similar-1.png');?>" alt="">
						</a>                
					</div> 
					<h5 class="design-name" style=""><a href="#" title="">VolksWagen 'Hipple' Camper</a></h5>
					<h6 class="design_sub_detail">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed</h6>
					<div class="price-box">
						<p class="special-price">
							<span class="price color-red">
								<span class="CurrencySymbol">₹</span>18,968
							</span>
						</p>
					</div>
				</div>
			</li>
			<li class="col-lg-3 col-md-3 col-sm-4 col-xs-6 "> 
				<div class="design-info">
					<div class="art-img-wrapper">
						<a href="#" title="" class="art-img">
							<img src="<?php echo $this->getViewFileUrl('RI_Artist::images/similar-1.png');?>" alt="">
						</a>                
					</div> 
					<h5 class="design-name" style=""><a href="#" title="">VolksWagen 'Hipple' Camper</a></h5>
					<h6 class="design_sub_detail">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed</h6>
					<div class="price-box">
						<p class="special-price">
							<span class="price color-red">
								<span class="CurrencySymbol">₹</span>18,968
							</span>
						</p>
					</div>
				</div>
			</li>
			<li class="col-lg-3 col-md-3 col-sm-4 col-xs-6 "> 
				<div class="design-info">
					<div class="art-img-wrapper">
						<a href="#" title="" class="art-img">
							<img src="<?php echo $this->getViewFileUrl('RI_Artist::images/similar-1.png');?>" alt="">
						</a>                
					</div> 
					<h5 class="design-name" style=""><a href="#" title="">VolksWagen 'Hipple' Camper</a></h5>
					<h6 class="design_sub_detail">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed</h6>
					<div class="price-box">
						<p class="special-price">
							<span class="price color-red">
								<span class="CurrencySymbol">₹</span>18,968
							</span>
						</p>
					</div>
				</div>
			</li>
			<li class="col-lg-3 col-md-3 col-sm-4 col-xs-6 "> 
				<div class="design-info">
					<div class="art-img-wrapper">
						<a href="#" title="" class="art-img">
							<img src="<?php echo $this->getViewFileUrl('RI_Artist::images/similar-1.png');?>" alt="">
						</a>                
					</div> 
					<h5 class="design-name" style=""><a href="#" title="">VolksWagen 'Hipple' Camper</a></h5>
					<h6 class="design_sub_detail">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed</h6>
					<div class="price-box">
						<p class="special-price">
							<span class="price color-red">
								<span class="CurrencySymbol">₹</span>18,968
							</span>
						</p>
					</div>
				</div>
			</li>
			<li class="col-lg-3 col-md-3 col-sm-4 col-xs-6 "> 
				<div class="design-info">
					<div class="art-img-wrapper">
						<a href="#" title="" class="art-img">
							<img src="<?php echo $this->getViewFileUrl('RI_Artist::images/similar-1.png');?>" alt="">
						</a>                
					</div> 
					<h5 class="design-name" style=""><a href="#" title="">VolksWagen 'Hipple' Camper</a></h5>
					<h6 class="design_sub_detail">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed</h6>
					<div class="price-box">
						<p class="special-price">
							<span class="price color-red">
								<span class="CurrencySymbol">₹</span>18,968
							</span>
						</p>
					</div>
				</div>
			</li>
		</ul>
	</div>
</div>