<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Wishlist\Block\Catalog\Product\View\Addto\Wishlist */

?>
<div class="product_wishlist">
<?php if ($block->isWishListAllowed()) : 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');

$om = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $om->create('Magento\Customer\Model\Session');
$arrOfProductIds=array();  
if($customerSession->isLoggedIn()) {
    
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    //Load product by product id
    $collection = $objectManager->create('Magento\Wishlist\Model\ResourceModel\Item\CollectionFactory')->create();
    //print_r($collection); exit();
    $collection->addCustomerIdFilter( $customerSession->getCustomer()->getId());
     foreach ($collection as $item) {
            $arrOfProductIds[] = $item->getProductId();
        } 
}
$currentProduct = json_decode($block->getWishlistParams());
$currentProductId = $currentProduct->data->product;

if( !in_array($currentProductId, $arrOfProductIds)){
?>
    <a id="loginpopup" href="#" title="Add to Wishlist" class="action towishlist" data-url="<?php echo $this->getUrl('wishlist/index/add');?>" data-post='<?php /* @escapeNotVerified */ echo $block->getWishlistParams(); ?>' data-action="add-to-wishlist"><span><i id="fillin" class="fa fa-heart-o" aria-hidden="true"></i></span></a>
    <?php } else{?>

    	 <a id="loginpopup" href="#" title="Add to Wishlist" class="action towishlist" data-url="<?php echo $this->getUrl('wishlist/index/add');?>" data-post='<?php /* @escapeNotVerified */ echo $block->getWishlistParams(); ?>' data-action="add-to-wishlist"><span><i id="fillin" class="fa fa-heart" aria-hidden="true"></i></span></a>
    
<?php } endif; ?>
</div>

<script type="text/x-magento-init">

    {
        "body": {
        	
            "addToWishlist": <?php /* @escapeNotVerified */  echo $block->getWishlistOptionsJson(); ?>
        	
        }
    }
        
</script>


