<?php
    $categories = $this->getCategoryCollection();
    $categoryHelper = $this->getCategoryHelper();
?>
<div class="widget block block-static-block cwiw" id="catewithimg">
    <div class="block-content">
        <?php
        foreach($categories as $category):
            $cat = $this->getCategorymodel($category->getId());
        ?>
			<div class="col-md-4">
				<a class="category_name" href="<?php echo $cat->getUrl(); ?>">
					<span><?php echo $cat->getName(); ?></span>
				</a>
			</div>
        <?php endforeach; ?>
    </div>
</div>
