<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Wishlist\Block\Customer\Sidebar */
?>
<?php
$wishlistHelper = $this->helper('Magento\Wishlist\Helper\Data');
?>
<?php if ($wishlistHelper->isAllow()) : ?>
    <div class="block block-wishlist" data-bind="scope: 'wishlist'">
        <div class="dash-info-title">
			<h3> My Wishlist</h3>
		</div>
        <div class="block-content">
			<div class="recent-orders-discription">
				<div class="recent-orders-footer">
					<div class="row">
						<div class="col-md-6 col-sm-6 col-xs-6">
							<h6>Product</h6>
						</div>
						<div class="col-md-2 col-sm-2 col-xs-2">
							<h6 class="hidden-xs">Qty</h6>
						</div>
						<div class="col-md-4 col-sm-4 col-md-4">
							<h6 class="hidden-xs">Price</h6>
						</div>
							
						<div class="col-md-4 hidden-xs">
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6 col-sm-6 col-xs-6">
						<div class="row">
							<div class="col-md-2">
								<img src="<?php echo $this->getViewFileUrl('Magento_Catalog::images/images/product-info.png');?>" alt="">
							</div>
							<div class="col-md-10">
								<div class="recent-orders-header-description">
									<h4>The Trabola</h4>
									<p>Lorem ipsum dolor sit amet, consectetuer Lorem ipsum dolor sit amet, consectetuer</p>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-1 col-sm-1 col-xs-1 recent-orders-footer-description">
						<h3 class="hidden-lg hidden-md">Qty</h3>
						<h3>1</h3>
					</div>
					<div class="col-md-1 col-sm-1 col-xs-1 recent-orders-footer-description">
						<h4 class="hidden-lg hidden-md">Price</h4>
						<h4>Rs.1500</h4>
					</div>
					<div class="col-md-4 col-sm-4 col-xs-4">
						<div class="recent-orders-footer-btn">
							<a href="#">Add to bag</a>
							<i class="fa fa-times" aria-hidden="true"></i>
						</div>
					</div>
				</div>
			</div>
			<div class="footer-container">
				<a href="#">Add all	to bag <i class="fa fa-chevron-right" aria-hidden="true"></i></a>
			</div>
            <!-- ko if: wishlist().counter -->
                <!--<ol class="product-items no-display" id="wishlist-sidebar" data-bind="foreach: wishlist().items, css: {'no-display': null}">
                    <li class="product-item">
                        <div class="product-item-info">
                            <a class="product-item-photo" data-bind="attr: { href: product_url, title: product_name }">
                                <!-- ko template: {name: $data.image.template, data: $data.image} --><!-- /ko --
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a data-bind="attr: { href: product_url }" class="product-item-link">
                                        <span data-bind="text: product_name"></span>
                                    </a>
                                </strong>
                                <div data-bind="html: product_price"></div>
                                <div class="product-item-actions">
                                    <!-- ko if: product_is_saleable_and_visible --
                                    <div class="actions-primary">
                                        <!-- ko if: product_has_required_options --
                                        <a href="#" data-bind="attr: {'data-post': add_to_cart_params}" class="action tocart primary"><span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span></a>
                                        <!-- /ko -->
                                        <!-- ko ifnot: product_has_required_options --
                                            <button type="button" class="action tocart primary" data-bind="attr: {'data-post': add_to_cart_params}"><span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span></button>
                                        <!-- /ko --
                                    </div>
                                    <!-- /ko --
                                    <div class="actions-secondary">
                                        <a href="#"  data-bind="attr: {'data-post': delete_item_params}"
                                           title="<?php /* @escapeNotVerified */ echo __('Remove This Item') ?>"
                                           class="btn-remove action delete">
                                            <span><?php /* @escapeNotVerified */ echo __('Remove This Item') ?></span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                </ol>-->
                <div class="actions-toolbar no-display" data-bind="css: {'no-display': null}">
                    <div class="primary">
                        <a class="action details"
                           href="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Wishlist\Helper\Data')->getListUrl() ?>"
                           title="<?php /* @escapeNotVerified */ echo __('Go to Wish List') ?>"><span><?php /* @escapeNotVerified */ echo __('Go to Wish List') ?></span></a>
                    </div>
                </div>
            <!-- /ko -->
            <!-- ko ifnot: wishlist().counter -->
                <!--<div class="empty"><?php /* @escapeNotVerified */ echo __('You have no items in your wish list.') ?></div>-->
            <!-- /ko -->
        </div>
    </div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "wishlist": {
                        "component": "Magento_Wishlist/js/view/wishlist"
                    }
                }
            }
        }
    }
</script>
<?php endif ?>
