<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Temlate for \Magento\Customer\Block\Address\Book block
 * @var $block \Magento\Customer\Block\Address\Book
 */
?>
<div class="block-dashboard-addresses get_link" id="addressbook">
	<div class="dash-info-title">
		<div class="head-secson">
			<img class="heding-icon" src="<?php echo $this->getViewFileUrl('Magento_Customer::images/address-book.png');?>" alt="image">
			<span class="heading">
				<span class="main-head"><?php /* @escapeNotVerified */ echo __('Address Book') ?></span>
				<span class="sub-head">Add or Edit your Address</span>
			</span>
		</div>
	</div>
	<div class="title-address-book">
		<?php if ($_pAddsses = $block->getDefaultBilling()): ?>
			<div class="box box-address-billing">
				<div class="title-address-container">
					<h3><?php /* @escapeNotVerified */ echo __('Default Billing Address') ?></h3>
				</div>
				<div class="row title-address-description">
					<div class="col-md-2">
						<h3><?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
								$customerSession = $objectManager->create('Magento\Customer\Model\Session');
								if ($customerSession->isLoggedIn()) {
									$custname=(string)$customerSession->getCustomer()->getName();
									echo $custname;
									}
							?>
						</h3>
					</div>
					<div class="col-md-6">
						<!-- <div class="address-location defaul-add">Home</div> -->
						<p class="whole-add"><?php echo $block->getAddressHtml($block->getAddressById($_pAddsses)) ?></p>
					</div>
					<div class="col-md-2">
						
					</div>
					<div class="col-md-2">
						<h4><a class="action edit" href="<?php echo $block->getAddressEditUrl($_pAddsses) ?>">Edit <i class="fa fa-angle-right" aria-hidden="true"></i></a></h4>
					</div>
				</div>
			</div>
		<?php else: ?>
			<div class="box box-billing-address">
				<div class="title-address-container">
					<h3><?php /* @escapeNotVerified */ echo __('Default Billing Address') ?></h3>
				</div>
				<div class="row title-address-description">
					<p><?php /* @escapeNotVerified */ echo __('You have no default billing address in your address book.') ?></p>
				</div>
			</div>
		<?php endif ?>
	</div>
	<div class="title-address-book">
		<?php if ($_pAddsses = $block->getDefaultShipping()): ?>
		<div class="box box-address-shipping">
			<div class="title-address-container">
					<h3><?php /* @escapeNotVerified */ echo __('Default Shipping Address') ?></h3>
				</div>
			<div class="row title-address-description">
				<div class="col-md-2">
					<h3><?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
							$customerSession = $objectManager->create('Magento\Customer\Model\Session');
							if ($customerSession->isLoggedIn()) {
								$custname=(string)$customerSession->getCustomer()->getName();
								echo $custname;
								}
						?>
					</h3>
				</div>
				<div class="col-md-6">
					<!-- <div class="address-location other-add">Tom's Office</div> -->
					<p class="whole-add"><?php echo $block->getAddressHtml($block->getAddressById($_pAddsses)) ?></p>
				</div>
				<div class="col-md-2">
					<!-- <h4><a href="">Make it default <i class="fa fa-angle-right" aria-hidden="true"></i></a></h4> -->
				</div>
				<div class="col-md-2">
					<h4><a class="action edit" href="<?php /* @escapeNotVerified */ echo $block->getAddressEditUrl($_pAddsses) ?>">Edit <i class="fa fa-angle-right" aria-hidden="true"></i></a></h4>
				</div>
			</div>
		</div>
		<?php else: ?>
			<div class="box box-shipping-address">
				<div class="title-address-container">
					<h3><?php /* @escapeNotVerified */ echo __('Default Shipping Address') ?></h3>
				</div>
				<div class="row title-address-description">
					<p><?php /* @escapeNotVerified */ echo __('You have no default shipping address in your address book.') ?></p>
				</div>
			</div>
		<?php endif ?>
	</div>

	<div class="other-addresses-list">
		<div class="block-content">
			<?php if ($_pAddsses = $block->getAdditionalAddresses()): ?>
				<ol class="items addresses">
					<?php foreach ($_pAddsses as $_address): ?>
						<div class="title-address-book-second">
							<div class="row title-address-description">
								<div class="col-md-2">
									<h3><?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
											$customerSession = $objectManager->create('Magento\Customer\Model\Session');
											if ($customerSession->isLoggedIn()) {
												$custname=(string)$customerSession->getCustomer()->getName();
												echo $custname;
												}
										?>
									</h3>
								</div>
								<div class="col-md-6">
									<!-- <div class="address-location other-add">Tom's Office</div> -->
									<p class="whole-add"><?php echo $block->getAddressHtml($_address) ?></p>
								</div>
								<div class="col-md-2">
									<!-- <h4><a href="">Make it default <i class="fa fa-angle-right" aria-hidden="true"></i></a></h4> -->
								</div>
								<div class="col-md-2">
									<h4><a class="action edit" href="<?php /* @escapeNotVerified */ echo $block->getUrl('customer/address/edit', ['id' => $_address->getId()]) ?>">Edit <i class="fa fa-angle-right" aria-hidden="true"></i></a></h4>
								</div>
							</div>
						</div>
					<?php endforeach; ?>
				</ol>
			<?php else: ?>
			<div class="title-address-book-second">
				<div class="row title-address-description">
					<p class="empty"><?php /* @escapeNotVerified */ echo __('You have no other address entries in your address book.') ?></p>
				</div>
			</div>
			<?php endif ?>
		</div>
	</div>
	
	<div class="title-address-book-second">
		<div class="title-address-description-last">
			<button type="button" role="add-address" title="<?php /* @escapeNotVerified */ echo __('Add New Address') ?>" class="edit action primary add"><img src="<?php echo $this->getViewFileUrl('images/add-new.png');?>" alt="image"><span><?php /* @escapeNotVerified */ echo __('Add New Address') ?></span></button>
		</div>
	</div>
</div>
<script type="text/x-magento-init">
    {
        ".page-main": {
            "address": {
                "deleteAddress": "li.item a[role='delete-address']",
                "deleteUrlPrefix": "<?php /* @escapeNotVerified */ echo $block->getDeleteUrl() ?>id/",
                "addAddress": "button[role='add-address']",
                "addAddressLocation": "<?php /* @escapeNotVerified */ echo $block->getAddAddressUrl() ?>"
            }
        }
    }
</script>
