
<!--   ******** Awards Section **********   -->

<div class="awards-container section-cotainer">
	<div class="awards-content">
		<div class="awards-grid grid-2">
			<div class="grid">
				<div class="award-block">
					<div class="award-left">
						<img src="<?php echo $this->getViewFileUrl('images/award1.jpg');?>">
					</div>
					<div class="award-right">
						<div class="awards-name">
							<h3>Reddot Design Awards</h3>
						</div>
						<div class="stars">
							<img src="<?php echo $this->getViewFileUrl('images/stars.jpg');?>">
						</div>
						<div class="awarded-product-name">
							<strong>IHORN.THE ACOUSTIC <br> MEGAPHONE</strong>
						</div>
						<div class="award-description">
							<span>Winner <br> Products design and innovation</span>
						</div>
					</div>
				</div>
			</div>
			
			<div class="grid">
				<div class="award-block">
					<div class="award-left">
						<img src="<?php echo $this->getViewFileUrl('images/award2.jpg');?>">
					</div>
					<div class="award-right">
						<div class="awards-name">
							<h3>Reddot Design Awards</h3>
						</div>
						<div class="stars">
							<img src="<?php echo $this->getViewFileUrl('images/stars.jpg');?>">
						</div>
						<div class="awarded-product-name">
							<strong>IHORN.THE ACOUSTIC <br> MEGAPHONE</strong>
						</div>
						<div class="award-description">
							<span>Winner <br> Products design and innovation</span>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

