<?php /*<!-- Shipping and fetured block--> */?>

<div class="footer-shipping-feture-container section-cotainer">
	<div class="footer-shipping-feture-content">
		<div class="columns-grid grid-4">
			<div class="grid">
				<div class="feture-content">
					<div class="icon-block">
						<img src="<?php echo $this->getViewFileUrl('images/shipping.jpg');?>"/>
					</div>
					<div class="feature-text">
						<span>Free shipping <br/>all over India</span>
					</div>
				</div>
			</div>
			<div class="grid">
				<div class="feture-content">
					<div class="icon-block">
						<img src="<?php echo $this->getViewFileUrl('images/clock.jpg');?>"/>
					</div>
					<div class="feature-text">
						<span>Product Delivery <br/>2-3 working days</span>
					</div>
				</div>
			</div>
			<div class="grid">
				<div class="feture-content">
					<div class="icon-block">
						<img src="<?php echo $this->getViewFileUrl('images/replace.jpg');?>"/>
					</div>
					<div class="feature-text">
						<span>7 Days no question asked <br/>replacement warranty</span>
					</div>
				</div>
			</div>
			<div class="grid">
				<div class="feture-content">
					<div class="icon-block">
						<img src="<?php echo $this->getViewFileUrl('images/payment.jpg');?>"/>
					</div>
					<div class="feature-text">
						<span>Accepts all mazor credits/debit <br/>cards for payments</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>