<?php /*<!-- ************************* Testimonial Block ************************* --> */?>

<div class="testimonial-container section-cotainer">
	<div class="testimonial-content">
		<div class="testimonial-slider" id="testimonial-slider">
			<div class="items">
				<div class="testimonial-box">
					<div class="quote-icon">
						<img class="quote" src="<?php echo $this->getViewFileUrl('images/quote.jpg');?>">
					</div>
					<div class="quote-content">
						<div class="quote-text">
							<span>"DesireDesire matches the vocabulary synonyms wish, want, longing, yearing, aspiration, fascination, inclination... the list is long."</span>
						</div>
						<div class="quote-writer">
							<span class="writer">
								Khizir Jaffri
							</span><br/>
							<span class="post-name">
								BLOGGER
							</span>
						</div>
					</div>
				</div>
			</div>
			<div class="items">
				<div class="testimonial-box">
					<div class="quote-icon">
						<img class="quote" src="<?php echo $this->getViewFileUrl('images/quote.jpg');?>">
					</div>
					<div class="quote-content">
						<div class="quote-text">
							<span>"DesireDesire matches the vocabulary synonyms wish, want, longing, yearing, aspiration, fascination, inclination... the list is long."</span>
						</div>
						<div class="quote-writer">
							<span class="writer">
								Khizir Jaffri
							</span><br/>
							<span class="post-name">
								BLOGGER
							</span>
						</div>
					</div>
				</div>
			</div>
			<div class="items">
				<div class="testimonial-box">
					<div class="quote-icon">
						<img class="quote" src="<?php echo $this->getViewFileUrl('images/quote.jpg');?>">
					</div>
					<div class="quote-content">
						<div class="quote-text">
							<span>"DesireDesire matches the vocabulary synonyms wish, want, longing, yearing, aspiration, fascination, inclination... the list is long."</span>
						</div>
						<div class="quote-writer">
							<span class="writer">
								Khizir Jaffri
							</span><br/>
							<span class="post-name">
								BLOGGER
							</span>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>