<?php /* <!--       Welcode Massege Box Start Here         --> */ ?>

<div class="welcome-box-container">
	<div class="welcome-box">
		<div class="scroll-down">
			<a href="javascript:void(0)" onclick="smoothScroll(document.getElementById('welcome-text'))">
				<img src="<?php echo $this->getViewFileUrl('images/scroll-down.jpg');?>" alt="scroll down"/>
			</a>
		</div>
		<div class="welcome-text" id="welcome-text">
			Welcome to <span style="color:#ff685b">Desire Desire,</span><br/>
			For the aesthete, there’s no greater joy than appreciating beauty.<br/>Which is what makes Desire Desire an unending delight. With joyfully curated products that bring beauty and design to objects we use daily.<br/>Go ahead, surround yourself with the <span class="red">antiordinary</span>.
		</div>
	</div>
</div>

<?php /* <!--       Welcode Massege Box end Here         --> */ ?>