<?php /* <!--       Welcode Massege Box Start Here         --> */ ?>

<div class="welcome-box-container">
	<div class="welcome-box">
		<div class="scroll-down">
			<a href="javascript:void(0)" onclick="smoothScroll(document.getElementById('welcome-text'))">
				<img src="<?php echo $this->getViewFileUrl('images/scroll-down.jpg');?>" alt="scroll down"/>
			</a>
		</div>
		<div class="welcome-text" id="welcome-text">
			Welcome to <span style="color:#ff685b">Desire Desire,</span><br/>
			your one stop destination for an alternative shopping experience. Whether you're looking for headphones for the audiophile, speakers for the travel or mobile cases to showcase your personality, you will find everything in our specially curated range of <span style="color:#ff685b">AntiOrdinary</span> and uniqe products. 
		</div>
	</div>
</div>

<?php /* <!--       Welcode Massege Box end Here         --> */ ?>