<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block newsletter">
    <div class="title"><strong>Newsletter</strong></div>
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="field newsletter">
                <label class="newsletter-large-text" for="newsletter">
					<strong class="large-text"><?php /* @escapeNotVerified */ echo __('BE THE FIRST!') ?></strong><br/><br/>
					<span><?php /* @escapeNotVerified */ echo __('Sign up, get on our exclusive list for offers, launch alerts and more.') ?></span>
				</label>
                <div class="control">
                    <input name="email" type="email" id="newsletter" onfocus="this.placeholder = ''" onblur="this.placeholder = 'enter email'" placeholder="<?php /* @escapeNotVerified */ echo __('enter email') ?>" data-validate="{required:true, 'validate-email':true}"/>
                    <div class="actions">
                    <button style="display:block" class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                    <span><i class="fa fa-angle-right" aria-hidden="true"></i></span>
                    </div>
                </div>
            </div>
           <!--  <div class="actions">
                <button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                    <span><i class="fa fa-angle-right" aria-hidden="true"></i></span>
                </button>
            </div> -->
        </form>
    </div>
</div>
