<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Dashboard\Address $block */
?>
<div class="block block-dashboard-addresses" id="page3">
	<a name="addressbook"></a>
	<div class="dash-info-title"><h3><?php /* @escapeNotVerified */ echo __('Address Book') ?></h3></div>
	<div class="title-address-book">
		<div class="title-address-container">
			<h3><?php /* @escapeNotVerified */ echo __('Default Address') ?></h3>
		</div>
		<div class="row title-address-description">
			<div class="col-md-2">
				<h3><?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
						$customerSession = $objectManager->create('Magento\Customer\Model\Session');
						if ($customerSession->isLoggedIn()) {
							$custname=(string)$customerSession->getCustomer()->getName();
							echo $custname;
							}
					?>
				</h3>
			</div>
			<div class="col-md-6">
				<p><?php echo $block->getPrimaryBillingAddressHtml() ?></p>
			</div>
			<div class="col-md-2">
				
			</div>
			<div class="col-md-2">
				<h4><a class="action edit" href="<?php /* @escapeNotVerified */ echo $block->getPrimaryBillingAddressEditUrl() ?>" data-ui-id="default-billing-edit-link">Edit <i class="fa fa-chevron-right" aria-hidden="true"></i></a></h4>
			</div>
		</div>
	</div>
	<div class="title-address-book-second">
		<div class="row title-address-description">
			<div class="col-md-2">
				<h3><?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
						$customerSession = $objectManager->create('Magento\Customer\Model\Session');
						if ($customerSession->isLoggedIn()) {
							$custname=(string)$customerSession->getCustomer()->getName();
							echo $custname;
							}
					?>
				</h3>
			</div>
			<div class="col-md-6">
				<p><?php echo $block->getPrimaryShippingAddressHtml() ?></p>
			</div>
			<div class="col-md-2">
				<h4>Make it default <i class="fa fa-chevron-right" aria-hidden="true"></i></h4>
			</div>
			<div class="col-md-2">
				<h4><a class="action edit" href="<?php /* @escapeNotVerified */ echo $block->getPrimaryShippingAddressEditUrl() ?>" data-ui-id="default-billing-edit-link">Edit <i class="fa fa-chevron-right" aria-hidden="true"></i></a></h4>
			</div>
		</div>
	</div>
	<div class="title-address-book-second">
		<div class="row title-address-description">
			<div class="col-md-2">
				<h3>Tom Jose</h3>
			</div>
			<div class="col-md-6">
				<p>#22, Haskar Hosur Road, 2nd Floor, Opp. Adugodi police station, Bangalore, Karnataka 560 030</p>
			</div>
			<div class="col-md-2">
				<h4>Make it default <i class="fa fa-chevron-right" aria-hidden="true"></i></h4>
			</div>
			<div class="col-md-2">
				<h4><a class="action edit" href="<?php /* @escapeNotVerified */ echo $block->getPrimaryBillingAddressEditUrl() ?>" data-ui-id="default-billing-edit-link">Edit <i class="fa fa-chevron-right" aria-hidden="true"></i></a></h4>
			</div>
		</div>
	</div>
	<div class="title-address-book-second">
		<div class="title-address-description-last">
			<a class="action edit" href="<?php /* @escapeNotVerified */ echo $block->getAddressBookUrl() ?>">
			<img src="<?php echo $this->getViewFileUrl('Magento_Catalog::images/images/.png');?>" alt="image"> 
			<p>Add new address</p></a>
		</div>
	</div>

    <!--<div class="block-title">
        <strong><?php /* @escapeNotVerified */ echo __('Address Book') ?></strong>
        <a class="action edit" href="<?php /* @escapeNotVerified */ echo $block->getAddressBookUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Manage Addresses') ?></span></a>
    </div>
    <div class="block-content">
        <div class="box box-billing-address">
            <strong class="box-title">
                <span><?php /* @escapeNotVerified */ echo __('Default Billing Address') ?></span>
            </strong>
            <div class="box-content">
                <address>
                    <?php echo $block->getPrimaryBillingAddressHtml() ?>
                </address>
            </div>
            <div class="box-actions">
                <a class="action edit" href="<?php /* @escapeNotVerified */ echo $block->getPrimaryBillingAddressEditUrl() ?>" data-ui-id="default-billing-edit-link"><span><?php /* @escapeNotVerified */ echo __('Edit Address') ?></span></a>
            </div>
        </div>
        <div class="box box-shipping-address">
            <strong class="box-title">
                <span><?php /* @escapeNotVerified */ echo __('Default Shipping Address') ?></span>
            </strong>
            <div class="box-content">
                <address>
                    <?php echo $block->getPrimaryShippingAddressHtml() ?>
                </address>
            </div>
            <div class="box-actions">
                <a class="action edit" href="<?php /* @escapeNotVerified */ echo $block->getPrimaryShippingAddressEditUrl() ?>" data-ui-id="default-shipping-edit-link"><span><?php /* @escapeNotVerified */ echo __('Edit Address') ?></span></a>
            </div>
        </div>
    </div>-->
</div>
