<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Temlate for \Magento\Customer\Block\Address\Book block
 * @var $block \Magento\Customer\Block\Address\Book
 */
?>
<div class="block-dashboard-addresses get_link" id="addressbook">
	<div class="show_adres">
		<div class="dash-title">
			<h3><?php echo __('Address Book') ?></h3>
		</div>
		<?php /* <div class="small_address">
			<?php
                if($_pAddsses = $block->getDefaultBilling()){ ?>
			<span>
				<?php
					$short_address = strip_tags($block->getAddressHtml($block->getAddressById($_pAddsses)));
					if (strlen($short_address) > 50) {
								$stringCut = substr($short_address, 0, 40);
								$short_address = substr($stringCut, 0, strrpos($stringCut, ' ')).'...'; 
							}
					echo $short_address;
					?>
			</span>
			<span class="address_tag">Home</span>
			<?php }else{ ?>
			<span><p><?php echo __('You have no default billing address in your address book.') ?></p></span>
				<?php } ?>
		</div> */ ?>
	</div>
	<div class="all_address">
		<div class="owl-carousel owl-theme">
			<div class="item">
				<?php if ($_pAddsses = $block->getDefaultBilling()): ?>
				<div class="box box-address-billing">
					<div class="row title-address-description">
						<div class="address_content">
							<p class="whole-add"><?php echo $block->getAddressHtml($block->getAddressById($_pAddsses)) ?></p>
						</div>
						
					</div>
					<div class="title-address-container">
						<h3><?php /* @escapeNotVerified */ echo __('Default Billing Address') ?></h3>
					</div>
				</div>
				<div class="edit_address">
					<h4><a class="action edit" href="<?php echo $block->getAddressEditUrl($_pAddsses) ?>">Edit <i class="fa fa-angle-right" aria-hidden="true"></i></a></h4>
				</div>
				<?php else: ?>
					<div class="box box-billing-address">
						<div class="row title-address-description">
							<p><?php /* @escapeNotVerified */ echo __('You have no default billing address in your address book.') ?></p>
						</div>
						<div class="title-address-container">
							<h3><?php /* @escapeNotVerified */ echo __('Default Billing Address') ?></h3>
						</div>
					</div>
					<div class="edit_address">
						<h4><a class="action edit" href="<?php echo $block->getAddressEditUrl($_pAddsses) ?>">Edit <i class="fa fa-angle-right" aria-hidden="true"></i></a></h4>
					</div>
				<?php endif ?>
			</div>
			<div class="item">
				<?php if ($_pAddsses = $block->getDefaultShipping()): ?>
				<div class="box box-address-billing">
					<div class="row title-address-description">
						<div class="address_content">
							<p class="whole-add"><?php echo $block->getAddressHtml($block->getAddressById($_pAddsses)) ?></p>
						</div>
					</div>
					<div class="title-address-container">
						<h3><?php /* @escapeNotVerified */ echo __('Default Shipping Address') ?></h3>
					</div>
				</div>
				<div class="edit_address">
					<h4><a class="action edit" href="<?php echo $block->getAddressEditUrl($_pAddsses) ?>">Edit <i class="fa fa-angle-right" aria-hidden="true"></i></a></h4>
				</div>
				<?php else: ?>
					<div class="box box-billing-address">
						<div class="row title-address-description">
							<p><?php /* @escapeNotVerified */ echo __('You have no default billing address in your address book.') ?></p>
						</div>
						<div class="title-address-container">
							<h3><?php /* @escapeNotVerified */ echo __('Default Shipping Address') ?></h3>
						</div>
					</div>
					<div class="edit_address">
						<h4><a class="action edit" href="<?php echo $block->getAddressEditUrl($_pAddsses) ?>">Edit <i class="fa fa-angle-right" aria-hidden="true"></i></a></h4>
					</div>
				<?php endif ?>
			</div>
			<?php if ($_pAddsses = $block->getAdditionalAddresses()): ?>
			<?php foreach ($_pAddsses as $_address): ?>
				<div class="item addresses">
					<div class="title-address-book-second">
						<div class="row title-address-description">
							<div class="address_content">
								<p class="whole-add"><?php echo $block->getAddressHtml($_address) ?></p>
							</div>
						</div>
						<div class="edit_address">
							<h4><a class="action edit" href="<?php echo $block->getAddressEditUrl($_pAddsses) ?>">Edit <i class="fa fa-angle-right" aria-hidden="true"></i></a></h4>
						</div>
					</div>
				</div>
			<?php endforeach; ?>
			<?php else: ?>
			<div class="title-address-book-second">
				<div class="row title-address-description">
					<p class="empty"><?php /* @escapeNotVerified */ echo __('You have no other address entries in your address book.') ?></p>
				</div>
			</div>
			<?php endif ?>
			<div class="item">
				<div class="title-address-book-second">
					<div class="title-address-description-last">
						<button type="button" role="add-address" title="<?php /* @escapeNotVerified */ echo __('Add New Address') ?>" class="edit action primary add"><img src="<?php echo $this->getViewFileUrl('images/add-new.png');?>" alt="image"><span><?php /* @escapeNotVerified */ echo __('Add New Address') ?></span></button>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>	
	
	
<script type="text/x-magento-init">
    {
        ".page-main": {
            "address": {
                "deleteAddress": "li.item a[role='delete-address']",
                "deleteUrlPrefix": "<?php /* @escapeNotVerified */ echo $block->getDeleteUrl() ?>id/",
                "addAddress": "button[role='add-address']",
                "addAddressLocation": "<?php /* @escapeNotVerified */ echo $block->getAddAddressUrl() ?>"
            }
        }
    }
</script>
<script>
require(['jquery'],function($){
    jQuery(document).ready(function(){
		jQuery(".show_adres").click(function(){
			jQuery(".show_adres").toggleClass('open');
			jQuery(".dash-title h3").toggleClass('clicked-titl');
			jQuery(".small_address").toggle();
			jQuery(".all_address").slideToggle(800);
		});
    });
});
</script>
<script>
require(['jquery','owl_carousel'],function($){
	$(document).ready(function() {
	  $('.all_address .owl-carousel').owlCarousel({
		loop: false,
		dots:false,
		nav:false,
		margin: 15,
		responsiveClass: true,
		stagePadding:30,
		items:1
	  })
	})
});
</script>