<div class="category-filter">
	<div class="filter_list col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<div class="filter_by_list">
			<div class="filter_name"> CASE TYPE</div>
			<div class="filter-data">
				<div class="filter-data-options">
					<ul>
						<li>Apple</li>
						<li>Aser</li>
						<li>Asus</li>
						<li>Gionee</li>
						<li>Google</li>
						<li>Intex</li>
						<li>Vivo</li>
						<li>HCL</li>
						<li>Samsung</li>
						<li>Mi</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="filter_by_list">
			<div class="filter_name"> CASE TYPE</div>
			<div class="filter-data">
				<div class="filter-data-options">
					<ul>
						<li>Apple</li>
						<li>Aser</li>
						<li>Asus</li>
						<li>Gionee</li>
						<li>Google</li>
						<li>Intex</li>
						<li>Vivo</li>
						<li>HCL</li>
						<li>Samsung</li>
						<li>Mi</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="filter_by_list">
			<div class="filter_name"> CASE TYPE</div>
			<div class="filter-data">
				<div class="filter-data-options">
					<ul>
						<li>Apple</li>
						<li>Aser</li>
						<li>Asus</li>
						<li>Gionee</li>
						<li>Google</li>
						<li>Intex</li>
						<li>Vivo</li>
						<li>HCL</li>
						<li>Samsung</li>
						<li>Mi</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>