
<div class="track_order_container">
	<div class="track_order-content">
		<div class="track_order_heading">
			<h4>Track Order</h4>
		</div>
        <?php
		$inc_id = $this->getRequest()->getParam('id');
		$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
		$storeManager = $objectManager->get("\Magento\Store\Model\StoreManagerInterface");
		$baseurl = $storeManager->getStore()->getBaseUrl();
		$_order = $objectManager->create('\Magento\Sales\Model\Order')->load($inc_id, 'increment_id');
		$_order->getShipmentsCollection();
		$ship_date = "";
		foreach($_order->getShipmentsCollection() as $shipment){
			    //$ship_date = $shipment->getCreatedAt();
			}
		$_shippingAddress = $_order->getShippingAddress();
		$orderDate = $_order->getCreatedAt();
		$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
		$connection = $resource->getConnection();
		$sql = "Select tracking_id FROM picker_shipping_info where Id=".$inc_id;
        $result = $connection->fetchAll($sql);
		$track_id = $result[0]['tracking_id'];
        $status = "";
		/* API Call*/
		$url = 'http://www.pickrr.com/api/tracking-json/';
       $data = array (
        'tracking_id' => $track_id
        );
        
	    $params = '';
	    foreach($data as $key=>$value)
	                $params .= $key.'='.$value.'&';

	        $params = trim($params, '&');

	    $ch = curl_init();
	    curl_setopt($ch, CURLOPT_URL, $url.'?'.$params ); //Url together with parameters
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); //Return data instead printing directly in Browser
	    curl_setopt($ch, CURLOPT_CONNECTTIMEOUT , 7); //Timeout after 7 seconds
	    curl_setopt($ch, CURLOPT_USERAGENT , "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1)");
	    curl_setopt($ch, CURLOPT_HEADER, 0);
	    $result = curl_exec($ch);
	    curl_close($ch);
	    $json = json_decode($result, true);
	    $main_status = $json['status']['current_status_type'];
	    if(!$main_status == "OP"){
			    for( $i = 0; $i<count(($json['track_arr'])); $i++ ){
			        $status = $json['track_arr'][$i]['status_array'][0]['status_body'];  
			     }
	    }
		?>
		<div class="track_order_data">
			<div class="order_id">
         	<span class="order_label">Order #: </span><span class="track_id"><?php echo $inc_id ?></span>
			</div>
			
			<div class="order-status col-lg-12 col-md-12 col-sm-12 col-xs-12">
				<div class="col-lg-3 col-md-3 col-sm-3 col-xs-4 status_state suct-class">
					<div class="track_line">
						<span class="order-crcl green"></span>
						<span class="order-tick"></span>
						<span class="order-red-line"></span>
					</div>
					<div class="order_tag">
						<span class="tag_label">Ordered:</span>
						<span class="tag_data"><?php echo date('d M Y' , strtotime($orderDate)) ?></span>
					</div>
				</div>
				<?php 
				if($status == "Order cancelled"){ ?>
				<div class="col-lg-3 col-md-3 col-sm-3 col-xs-4 status_state suct-class">
					<div class="track_line">
						<span class="order-crcl green"></span>
						<span class="order-tick"></span>
						<span class=""></span>
					</div>
					<div class="order_tag">
						<span class="tag_label">Cancelled:</span>
						<span class="tag_data"></span>
					</div>
				</div>
				<?php }else { ?>
				<div class="col-lg-3 col-md-3 col-sm-3 col-xs-4 status_state suct-class">
					<div class="track_line">
						<span class="order-crcl"></span>
					              <span class="order-tick <?php if($main_status == 'PP'){ echo 'green'; } ?> "></span>
						<span class="order-red-line"></span>
					</div>
					<div class="order_tag">
						<span class="tag_label">Shipped:</span>
						<span class="tag_data">
						<?php
                         if(!$ship_date == ""){
                         	echo date('d M Y' , strtotime($ship_date));
                         }
						 ?></span>
					</div>
				</div>
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-4 status_state right_align suct-class">
					<div class="track_line">
						<span class="order-crcl"></span>
						<span class="order-tick <?php if($main_status == 'DL'){ echo 'green'; } ?> "></span>
						<span class="order-red-line"></span>
					</div>
					<div class="order_tag">
						<span class="tag_label">
                        <?php if($main_status == 'DL'){ ?>
						Delivered
						<?php }else{ ?>
						Est. Delivery:
						<?php } ?>
					</span>
						<?php
						$date = strtotime($orderDate);
						$date = strtotime("+7 day", $date);
                         $tomorrow_date = date("d M Y", $date);
                         if($main_status != 'DL'){
						 ?>
						<span class="tag_data"><?php echo $tomorrow_date  ?></span>
						<?php } ?>
					</div>
				</div>
				<?php } ?>
				<div class="col-lg-3 col-md-3 col-sm-3 col-xs-4 status_state second-line">
					<div class="order_tag">
						<span class="tag_label">Ship to:</span>
						<span class="tag_data">
							<span class="cst_name"><?php echo $_shippingAddress->getFirstname().' '.$_shippingAddress->getLastname() ?></span>
							<span class="cst_address">
					<?php echo $_shippingAddress->getCity().','.$_shippingAddress->getRegion().'<br />
                            '.$_shippingAddress->getPostcode().'<br />
                            '.$_shippingAddress->getTelephone() ?></span>
						</span>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 col-xs-4 status_state second-line">
					<span class="shipped_prodcut">
						<?php
						$order = $objectManager->create("Magento\Sales\Model\Order")->load($_order->getId());
                        $orderItems = $order->getAllItems();
						foreach ($orderItems as $_item) {
                           $productid = $_item->getProductId();
                           $product = $objectManager->create("Magento\Catalog\Model\Product")->load($productid);
                           ?>
                <img src="<?php echo $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA).'catalog/product'.$product->getData('image') ?>" alt="img">
                           <?php
                            } 
						 ?>
					</span>
				</div>
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-4 status_state mob-sec second-line">
<div class="order_detail_link"><a href="<?php echo $baseurl.'sales/order/view?order_id='.$_order->getId() ?>">Order Details</a><span class="rit-arrow"></span></div>
				</div>
			</div>
		</div>
	</div>
</div>
<style>
.order-crcl.green {
    background-color: green;
}
.suct-class{
	    padding: 0;
    height: 75px;
}
}

	</style>
