<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
$estimate =  date('j F Y', strtotime("+1 week"));

 ?>
<input type="hidden" id="estimate" value="<?php echo $estimate ?>">
<div id="checkout" data-bind="scope:'checkout'" class="checkout-container">
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
                 alt="<?php /* @escapeNotVerified */ echo __('Loading...'); ?>"
                 style="position: absolute;">
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
            }
        }
    </script>
    <script>
        window.checkoutConfig = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getCheckoutConfig()); ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
    </script>
    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>");
            return url.setBaseUrl('<?php /* @escapeNotVerified */ echo $block->getBaseUrl();?>');
        })
    </script>
</div>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$cust_mail = $customerSession->getCustomer()->getEmail();
$shippingID =  $customerSession->getCustomer()->getDefaultShipping();
$address = $objectManager->create('Magento\Customer\Model\Address')->load($shippingID);
?>
<input type="hidden" value="<?php echo $cust_mail; ?>" id="custom_mail">
<input type="hidden" value="<?php echo $address->getPostcode(); ?>" id="custom-zip">
<input type="hidden" value="" id="custom-mobile">
<?php
if(!$customerSession->isLoggedIn()) {
?>
<input type="hidden" id="log_act" value="no">
<style>
.loading-mask{
background:none !important;
}
#custom-social {
    background: #fff;
    top: 170px;
    position: absolute;
}
#custom-social .white-popup {
    position: relative;
    background: #FFF;
    padding: 0;
    width: auto;
	min-width:560px;
	margin:0;
	border-radius:5px;
}
#custom-social #social-login-popup .social-login-title {
    border-top-left-radius: 5px;
	border-bottom-left-radius: 5px;
}
#checkoutSteps {
    margin-top: 400px;
	pointer-events: none;
    opacity: 0.3;
}
#custom-social {
    background: #fff;
	z-index:1;
    top: 170px;
    position: absolute;
    box-shadow: 5px 7px 20px 10px rgba(0, 0, 0, 0.1);
    border-radius: 5px;
}
.checkout-index-index form.form.form-login {
display: none;
}
</style>
<?php
}else{
 ?>
 <input type="hidden" id="log-act" value="yes">
<?php } ?>
    <?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $bse = $storeManager->getStore()->getBaseUrl();
    ?>
<input type="hidden" id="baseurl" value="<?php echo $bse; ?>">
