<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Catalog\Block\Product\AbstractProduct */ ?>
<div class="review_sec">

<?php echo $block->getReviewsSummaryHtml($block->getProduct(), false, true)?>

<div class="delivery_chagre">
	<span class="delivery-options">Free Delivery</span>
</div>

</div>
